= dnf Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

The cheat sheet describes the various ways the command `dnf` can be used to install and inspect applications running on the Red Hat Enterprise Linux operating system. The term `dnf` is an abbreviation for *Dandified yum*. You can think of `dnf` as the next generation of the yum package manager.

The general usage for `dnf` is

----
dnf [options] <command> <subcommand>
----

== Module Exploration Commands

The following shows how to use `dnf module` to get information about various RHEL modules.

=== dnf module info

----
dnf module info <module_name>
----

*Examples:*

----
$ dnf module info cri-o
Not root, Subscription Management repositories not updated
Last metadata expiration check: 0:00:16 ago on Thu 27 Jan 2022 11:24:52 AM PST.
Name             : cri-o
Stream           : 1.21
Version          : 820210916195922
Context          : 9edba152
Architecture     : x86_64
Profiles         : default [d]
Default profiles : default
Repo             : epel-modular
Summary          : Kubernetes Container Runtime Interface for OCI-based containers
Description      : CRI-O is the Kubernetes Container Runtime Interface for OCI-based containers.
Requires         : platform:[el8]
Artifacts        : cri-o-0:1.21.3-1.module_el8+12969+ebff6d46.src
                 : cri-o-0:1.21.3-1.module_el8+12969+ebff6d46.x86_64
                 : cri-o-debuginfo-0:1.21.3-1.module_el8+12969+ebff6d46.x86_64
                 : cri-o-debugsource-0:1.21.3-1.module_el8+12969+ebff6d46.x86_64
                 : cri-tools-0:1.19.0-1.module_el8+12969+ebff6d46.src
                 : cri-tools-0:1.19.0-1.module_el8+12969+ebff6d46.x86_64
                 : cri-tools-debuginfo-0:1.19.0-1.module_el8+12969+ebff6d46.x86_64
                 : cri-tools-debugsource-0:1.19.0-1.module_el8+12969+ebff6d46.x86_64

Hint: [d]efault, [e]nabled, [x]disabled, [i]nstalled, [a]ctive
----

TO BE PROVIDED

----
$ dnf module info --profile ruby:2.6 -v
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, kpatch, needs-restarting, playground, product-id, repoclosure, repodiff, repograph, repomanage, reposync, subscription-manager, uploadprofile
Not root, Subscription Management repositories not updated
DNF version: 4.7.0
cachedir: /var/tmp/dnf-reselbob-ovrcuzk9
User-Agent: constructed: 'libdnf (Red Hat Enterprise Linux 8.5; generic; Linux.x86_64)'
repo: using cache for: epel
epel: using metadata from Wed 26 Jan 2022 10:00:39 AM PST.
repo: using cache for: epel-modular
epel-modular: using metadata from Tue 25 Jan 2022 04:15:30 PM PST.
repo: using cache for: rhel-8-for-x86_64-baseos-rpms
rhel-8-for-x86_64-baseos-rpms: using metadata from Tue 25 Jan 2022 11:34:54 AM PST.
repo: using cache for: rhel-8-for-x86_64-appstream-rpms
rhel-8-for-x86_64-appstream-rpms: using metadata from Thu 27 Jan 2022 06:01:31 AM PST.
Last metadata expiration check: 0:03:07 ago on Thu 27 Jan 2022 11:24:52 AM PST.
Unable to resolve argument info

document: modulemd
version: 2
data:
  name: ruby
  stream: "2.6"
  version: 8010020190711095715
  context: cdc1202b
.
.
.
----

=== dnf module list

`dnf module [options] list <module_name>`

This command reports the status of RHEL modules available from a remote RHEL repository or downloaded to the local computer. A module can have one or more of the following status: default (`d)`, enabled (`e`), disabled (`x`) or installed (`i`).

When the command is run as `sudo` the repository reference on the local machine will be updated.

*Examples:*

----
$ dnf module list | more -20
Not root, Subscription Management repositories not updated
Last metadata expiration check: 0:28:18 ago on Thu 27 Jan 2022 10:14:08 AM PST.
Extra Packages for Enterprise Linux Modular 8 - x86_64
Name                 Stream           Profiles                                 Summary                                                                                                                                   
                                                                                       
389-directory-server next             default, minimal                         389 Directory Server                                                                                                                      
                                                                                       
389-directory-server stable           default [d], legacy, minimal             389 Directory Server                                                                                                                      
                                                                                       
389-directory-server testing          default [d], legacy, minimal             389 Directory Server                                                                                                                      
                                                                                       
avocado              latest           default, minimal                         Framework with tools and libraries for Automated Testing                                                                                  
                                                                                       
avocado              82lts            default, minimal                         Framework with tools and libraries for Automated Testing                                                                                  
                                                                                       
avocado-vt           latest           default                                  Avocado Virt Test Plugin                                                                                                                  
                                                                                       
cobbler              3                default [d]                              Versatile Linux deployment server                                                                                                         
                                                                                       
cri-o                1.21             default [d]                              Kubernetes Container Runtime Interface for OCI-based containers                                                                           
--More--

----

TO BE PROVIDED

----
$ sudo dnf list installed | more -15
Updating Subscription Management repositories.
Installed Packages
GConf2.x86_64                                      3.2.6-22.el8                                   @AppStream                       
ModemManager.x86_64                                1.10.8-4.el8                                   @anaconda                        
ModemManager-glib.x86_64                           1.10.8-4.el8                                   @anaconda                        
NetworkManager.x86_64                              1:1.32.10-4.el8                                @anaconda                        
NetworkManager-adsl.x86_64                         1:1.32.10-4.el8                                @anaconda                        
NetworkManager-bluetooth.x86_64                    1:1.32.10-4.el8                                @anaconda                        
NetworkManager-config-server.noarch                1:1.32.10-4.el8                                @anaconda                        
NetworkManager-libnm.x86_64                        1:1.32.10-4.el8                                @anaconda                        
NetworkManager-team.x86_64                         1:1.32.10-4.el8                                @anaconda                        
NetworkManager-tui.x86_64                          1:1.32.10-4.el8                                @anaconda                        
NetworkManager-wifi.x86_64                         1:1.32.10-4.el8                                @anaconda                        
NetworkManager-wwan.x86_64                         1:1.32.10-4.el8                                @anaconda                        
PackageKit.x86_64                                  1.1.12-6.el8                                   @AppStream                       
--More--
----

=== dnf module provides

----
dnf module provides <module_name>
----

*Example:*

----
$ sudo dnf module provides cobbler
Updating Subscription Management repositories.
Last metadata expiration check: 1:59:10 ago on Thu 27 Jan 2022 08:48:07 AM PST.
cobbler-3.2.2-6.module_el8+13609+df89ec4a.noarch
Module   : cobbler:3:820220106021107:9edba152:x86_64
Profiles : default
Repo     : epel-modular
Summary  : Versatile Linux deployment server
----

== General dnf Commands

TO BE PROVIDED

=== dnf search 

`dnf search <string>`

*Example:*

----
$ dnf search nodejs
Not root, Subscription Management repositories not updated
Last metadata expiration check: 0:07:20 ago on Thu 27 Jan 2022 11:24:52 AM PST.
============= Name Exactly Matched: nodejs =============
nodejs.x86_64 : JavaScript runtime
============= Name & Summary Matched: nodejs =============
nodejs-GeographicLib.noarch : NodeJS implementation of GeographicLib
============= Name Matched: nodejs =============
nodejs-codemirror.noarch : A versatile JS text editor
nodejs-devel.x86_64 : JavaScript runtime - development headers
nodejs-docs.noarch : Node.js API documentation
nodejs-full-i18n.x86_64 : Non-English locale data for Node.js
nodejs-marked.noarch : A markdown parser for JavaScript built for speed
nodejs-nodemon.noarch : Simple monitor script for use during development of a node.js app
nodejs-packaging.noarch : RPM Macros and Utilities for Node.js Packaging
============= Summary Matched: nodejs =============
cjdns-tools.noarch : Nodejs tools for cjdns
----

=== dnf info 

Displays details about a module

----
dnf info <module-name>
----

*Example:*

The following example uses the command `dnf info` to display the details about the `dotnet`  module.

----
$ dnf info dotnet
Not root, Subscription Management repositories not updated
Last metadata expiration check: 0:41:52 ago on Tue 01 Feb 2022 09:19:22 AM PST.
Installed Packages
Name         : dotnet
Version      : 6.0.101
Release      : 2.el8_5
Architecture : x86_64
Size         : 0.0  
Source       : dotnet6.0-6.0.101-2.el8_5.src.rpm
Repository   : @System
From repo    : rhel-8-for-x86_64-appstream-rpms
Summary      : .NET CLI tools and runtime
URL          : https://github.com/dotnet/
License      : MIT and ASL 2.0 and BSD and LGPLv2+ and CC-BY and CC0 and MS-PL and EPL-1.0 and GPL+ and GPLv2 and ISC and OFL and zlib
Description  : .NET is a fast, lightweight and modular platform for creating
             : cross platform applications that work on Linux, macOS and Windows.
             : 
             : It particularly focuses on creating console applications, web
             : applications and micro-services.
             : 
             : .NET contains a runtime conforming to .NET Standards a set of
             : framework libraries, an SDK containing compilers and a 'dotnet'
             : application to drive everything.
----


=== dnf install

----
dnf install [options] <package_name>
----

Installs an application package on the local machine.

*Example:*

The following installs the`perl` programming language from the local computer. The command uses the `-y` option to suppress the prompt asking the user for permission to proceed.

The command produces too much screen output to show. 

----
sudo dnf install -y perl
----

=== dnf update

----
dnf update [options] <package_name>
----

Updates an application package on the local machine.

*Example:*

The following installs the`perl` programming language from the local computer. The command uses the `-y` option to suppress the prompt asking the user for permission to proceed.

----
$ sudo dnf update -y perl
Updating Subscription Management repositories.
Last metadata expiration check: 2:58:35 ago on Thu 27 Jan 2022 08:48:07 AM PST.
Dependencies resolved.
Nothing to do.
Complete!
----

----
sudo dnf update -y perl
----

=== dnf remove

----
dnf remove <package_name>
----

Removes an application package on the local machine.

*Example:*

The following removes the previously installed `perl` programming language from the local computer. The command produces too much screen output to show. 

----
sudo dnf update -y perl
----

=== dnf history

----
dnf [options] history <subcommand> <subcommand> ....
----

*Examples:*

TO BE PROVIDED

----
$ dnf history
----

TO BE PROVIDED

----
$ sudo dnf history undo last
----

=== dnf list all

----
dnf list all
----
TO BE PROVIDED

*Example:*

TO BE PROVIDED

=== dnf list installed

----
dnf list installed
----

TO BE PROVIDED

*Example:*

TO BE PROVIDED

=== dnf repolist

----
sudo dnf repolist
----

TO BE PROVIDED

*Example:*

TO BE PROVIDED

----
$ dnf repolist
Not root, Subscription Management repositories not updated
repo id                                                                                          repo name
epel                                                                                             Extra Packages for Enterprise Linux 8 - x86_64
epel-modular                                                                                     Extra Packages for Enterprise Linux Modular 8 - x86_64
rhel-8-for-x86_64-appstream-rpms                                                                 Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
rhel-8-for-x86_64-baseos-rpms 
----

== Subscription Manager Commands

----
subscription-manager command [options]
----

The command is a client-side program that provides a command line interface to the RHEL Subscription Management service. The Service Manager coordinates accessing, monitoring and getting information about RHEL applications and modules.

=== subscription-manager repos --enable repository

TO BE PROVIDED

*Examples:*

The following example uses the `repos` command to list the various artifact repository available via the Subscription Manager. The `repos` command requires root access. The command will problem for the root password if it is not executed as root.

The example belows shows only a portion of the full output.

----
$ subscription-manager repos
You are attempting to run "subscription-manager" which requires administrative
privileges, but more information is needed in order to do so.
Authenticating as "root"
Password: 
+----------------------------------------------------------+
    Available Repositories in /etc/yum.repos.d/redhat.repo
+----------------------------------------------------------+
Repo ID:   rhel-8-for-x86_64-sap-solutions-e4s-rpms
Repo Name: Red Hat Enterprise Linux 8 for x86_64 - SAP Solutions - Update Services for SAP Solutions (RPMs)
Repo URL:  https://cdn.redhat.com/content/e4s/rhel8/$releasever/x86_64/sap-solutions/os
Enabled:   0

Repo ID:   jpp-textonly-1-for-middleware-rpms
Repo Name: Red Hat JBoss Portal Text-Only Advisories
Repo URL:  https://cdn.redhat.com/content/dist/middleware/jpp/1.0/$basearch/os
Enabled:   0

Repo ID:   jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms
Repo Name: Red Hat JBoss Data Grid 8.1 (RHEL 8) (Source RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/jdg/8.1/source/SRPMS
Enabled:   0

Repo ID:   jb-datagrid-8.1-for-rhel-8-x86_64-debug-rpms
Repo Name: Red Hat JBoss Data Grid 8.1 (RHEL 8) (Debug RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/jdg/8.1/debug
Enabled:   0
.
.
.
----

The following example enables the client computer to access the repository `jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms`.

----
$ subscription-manager repos --enable jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms
You are attempting to run "subscription-manager" which requires administrative
privileges, but more information is needed in order to do so.
Authenticating as "root"
Password: 
Repository 'jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms' is enabled for this system.
----

The following example disables the client computer from accessing the repository `jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms`.

----
$ subscription-manager repos --disable jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms
You are attempting to run "subscription-manager" which requires administrative
privileges, but more information is needed in order to do so.
Authenticating as "root"
Password: 
Repository 'jb-datagrid-8.1-for-rhel-8-x86_64-source-rpms' is disabled for this system.
----

== General Module Commands

The following shows the various ways the command `dnf module` can be used to enable, install, and remove modules.

=== dnf module list

----
`dnf module [options] list`
----

Lists the modules available according to repositories registered with Subscription Manager

*Example:*

The follow shows a portions of the modules listed using the command `dnf module list`.

----
$ dnf module list
Not root, Subscription Management repositories not updated
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)      10 kB/s | 4.1 kB     00:00    
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)   13 kB/s | 4.5 kB     00:00    
Extra Packages for Enterprise Linux Modular 8 - x86_64
Name                 Stream           Profiles Summary                                                                                                                                                                   
389-directory-server next             default, 389 Directory Server                                                                                                                                                      
                                       minimal 
389-directory-server stable           default  389 Directory Server                                                                                                                                                      
                                      [d], leg 
                                      acy, min 
                                      imal     
389-directory-server testing          default  389 Directory Server                                                                                                                                                      
                                      [d], leg 
                                      acy, min 
                                      imal     
avocado              latest           default, Framework with tools and libraries for Automated Testing                                                                                                                  
                                       minimal 
avocado              82lts            default, Framework with tools and libraries for Automated Testing                                                                                                                  
                                       minimal 
avocado-vt           latest           default  Avocado Virt Test Plugin                                                                                                                                                  
cobbler              3                default  Versatile Linux deployment server                                                                                                                                         
                                      [d]      
cri-o                1.21             default  Kubernetes Container Runtime Interface for OCI-based containers                                                                                                           
                                      [d]      
dwm                  latest           default, Dynamic window manager for X                                                                                                                                              
                                       user    
ghc                  8.2              default  Haskell GHC 8.2                                                                                                                                                           
                                      [d], min 
                                      imal, sm 
                                      all      
ghc                  8.4              default  Haskell GHC 8.4                                                                                                                                                           
                                      [d], min 
                                      imal, sm 
                                      all      
----

=== dnf module enable module:stream

----
dnf module [options] enable <module:stream>
----

Enables a module.

*Example:*

TO BE PROVIDED

----
$ sudo dnf module enable scala:2.10
Updating Subscription Management repositories.
Last metadata expiration check: 0:18:54 ago on Fri 28 Jan 2022 11:32:49 AM PST.
Dependencies resolved.
================================================================================================
 Package                                             Architecture  Version   Repository  Size
================================================================================================
Enabling module streams:
 scala                                                              2.10                                                                                                            

Transaction Summary
================================================================================================

Is this ok [y/N]: 
Complete!
----

=== dnf module remove module

----
dnf module remove <module_name:stream>
----

Removes a module from the local environment

*Example:*

The following example removes the module `ant` from the local environment

----
$ sudo dnf remove ant
Updating Subscription Management repositories.
Dependencies resolved.
==================================================================
 Package                            Architecture                Version                                Repository                               Size
==================================================================
Removing:
 ant                                noarch                       1.10.5-1.module+el8+2438+c99a8a1e      @rhel-8-for-x86_64-appstream-rpms       451 k
Removing unused dependencies:
 ant-lib                            noarch                       1.10.5-1.module+el8+2438+c99a8a1e      @rhel-8-for-x86_64-appstream-rpms       2.2 M
 java-1.8.0-openjdk                 x86_64                       1:1.8.0.322.b06-2.el8_5                @rhel-8-for-x86_64-appstream-rpms       841 k
 java-1.8.0-openjdk-devel           x86_64                       1:1.8.0.322.b06-2.el8_5                @rhel-8-for-x86_64-appstream-rpms       41 M
 ttmkfdir                           x86_64                       3.0.9-54.el8                           @rhel-8-for-x86_64-appstream-rpms       128 k
 xorg-x11-fonts-Type1               noarch                       7.5-19.el8                             @rhel-8-for-x86_64-appstream-rpms       863 k

Transaction Summary
==================================================================

Freed space: 45 M
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                              1/1 
  Erasing          : ant-1.10.5-1.module+el8+2438+c99a8a1e.noarch                                                 1/6 
  Erasing          : java-1.8.0-openjdk-devel-1:1.8.0.322.b06-2.el8_5.x86_64                                      2/6 
  Running scriptlet: java-1.8.0-openjdk-devel-1:1.8.0.322.b06-2.el8_5.x86_64                                      2/6 
  Erasing          : ant-lib-1.10.5-1.module+el8+2438+c99a8a1e.noarch                                             3/6 
  Erasing          : java-1.8.0-openjdk-1:1.8.0.322.b06-2.el8_5.x86_64                                            4/6 
  Running scriptlet: java-1.8.0-openjdk-1:1.8.0.322.b06-2.el8_5.x86_64                                            4/6 
  Erasing          : xorg-x11-fonts-Type1-7.5-19.el8.noarch                                                       5/6 
  Running scriptlet: xorg-x11-fonts-Type1-7.5-19.el8.noarch                                                       5/6 
  Erasing          : ttmkfdir-3.0.9-54.el8.x86_64                                                                 6/6 
  Running scriptlet: ttmkfdir-3.0.9-54.el8.x86_64                                                                 6/6 
  Verifying        : ant-1.10.5-1.module+el8+2438+c99a8a1e.noarch                                                 1/6 
  Verifying        : ant-lib-1.10.5-1.module+el8+2438+c99a8a1e.noarch                                             2/6 
  Verifying        : java-1.8.0-openjdk-1:1.8.0.322.b06-2.el8_5.x86_64                                            3/6 
  Verifying        : java-1.8.0-openjdk-devel-1:1.8.0.322.b06-2.el8_5.x86_64                                      4/6 
  Verifying        : ttmkfdir-3.0.9-54.el8.x86_64                                                                 5/6 
  Verifying        : xorg-x11-fonts-Type1-7.5-19.el8.noarch                                                       6/6 
Installed products updated.

Removed:
  ant-1.10.5-1.module+el8+2438+c99a8a1e.noarch     ant-lib-1.10.5-1.module+el8+2438+c99a8a1e.noarch     java-1.8.0-openjdk-1:1.8.0.322.b06-2.el8_5.x86_64
  java-1.8.0-openjdk-devel-1:1.8.0.322.b06-2.el8_5.x86_64     ttmkfdir-3.0.9-54.el8.x86_64   xorg-x11-fonts-Type1-7.5-19.el8.noarch              

Complete!
----

=== dnf module disable module

----
dnf module disable <module_name:stream>
----

*Example:*

The following example disables them module `scala` for stream `2.10`.

----
$ sudo dnf module disable  scala:2.10
Updating Subscription Management repositories.
Last metadata expiration check: 0:18:31 ago on Tue 01 Feb 2022 09:09:19 AM PST.
Only module name is required. Ignoring unneeded information in argument: 'scala:2.10'
Dependencies resolved.
=====================================================================================
 Package                      Architecture        Version    Repository   Size
=====================================================================================
Disabling module profiles:
 scala/common                                                                                                                                                                                                           
Disabling modules:
 scala                                                                                                                                                                                                                  

Transaction Summary
======================================================================================
Is this ok [y/N]: y
Complete!
----

== Module Installation Commands

The following are application and module specific examples of using the command `dnf install`. Notice that the commands are run with administrator privileges using the `sudo` command.

----
sudo dnf install ant
----

----
sudo dnf install buildah podman
----

----
sudo dnf install llvm-toolset
----

----
sudo dnf group install "Development Tools"
----

----
sudo dnf install go-toolset
----

----
sudo dnf install httpd
----

----
sudo dnf install mariadb
----

----
sudo dnf install maven
----

----
sudo dnf install mysql
----

----
sudo dnf install nginx
----

----
sudo dnf install nodejs
----

----
sudo dnf install java-11-openjdk-devel
----

----
sudo dnf install java-1.8.0-openjdk-devel
----

----
sudo dnf install pcp-zeroconf
----

----
sudo dnf install perl
----

----
sudo dnf install php
----

----
sudo dnf install postgresql
----

----
sudo dnf module install postgresql:9.6
----

----
sudo dnf install python2 or dnf module install python27
----

----
sudo dnf install python3 or dnf module install python36
----

----
sudo dnf install redis
----

----
sudo dnf install ruby
----

----
sudo dnf install rust-toolset
----

----
sudo dnf install scala
----

----
sudo dnf install subversion
----

----
sudo dnf install swig
----

----
sudo dnf install systemtap
----

----
sudo dnf install valgrind
----

----
sudo dnf install varnish
----