= dnf Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

The cheat sheet describes the various ways the command `dnf` can be used to install and inspect applications running on the Red Hat Enterprise Linux operating system. The term `dnf` is an abbreviation for *Dandified yum*. You can think of `dnf` as the next generation of the yum package manager.

The general usage for `dnf` is

---
dnf [options] <command> <subcommand>
---

== Module Exploration Commands

The following shows how to use `dnf module` to get information about various RHEL modules.

=== dnf module list

---
dnf [options] module list
---

This command reports the status of RHEL modules available from a remote RHEL repository or downloaded to the local computer. A module can have one or more of the following status: default (`d)`, enabled (`e`), disabled (`x`) or installed (`i`).

When the command is run as `sudo` the repository reference on the local machine will be updated.

*Example:*

=== dnf module list installed

*Example:*

---
$ dnf module list | more -20
Not root, Subscription Management repositories not updated
Last metadata expiration check: 0:28:18 ago on Thu 27 Jan 2022 10:14:08 AM PST.
Extra Packages for Enterprise Linux Modular 8 - x86_64
Name                 Stream           Profiles                                 Summary                                                                                                                                   
                                                                                       
389-directory-server next             default, minimal                         389 Directory Server                                                                                                                      
                                                                                       
389-directory-server stable           default [d], legacy, minimal             389 Directory Server                                                                                                                      
                                                                                       
389-directory-server testing          default [d], legacy, minimal             389 Directory Server                                                                                                                      
                                                                                       
avocado              latest           default, minimal                         Framework with tools and libraries for Automated Testing                                                                                  
                                                                                       
avocado              82lts            default, minimal                         Framework with tools and libraries for Automated Testing                                                                                  
                                                                                       
avocado-vt           latest           default                                  Avocado Virt Test Plugin                                                                                                                  
                                                                                       
cobbler              3                default [d]                              Versatile Linux deployment server                                                                                                         
                                                                                       
cri-o                1.21             default [d]                              Kubernetes Container Runtime Interface for OCI-based containers                                                                           
--More--
---

=== dnf module provides

---
dnf module provides <package_name>
---

*Example:*

---
$ sudo dnf module provides cobbler
Updating Subscription Management repositories.
Last metadata expiration check: 1:59:10 ago on Thu 27 Jan 2022 08:48:07 AM PST.
cobbler-3.2.2-6.module_el8+13609+df89ec4a.noarch
Module   : cobbler:3:820220106021107:9edba152:x86_64
Profiles : default
Repo     : epel-modular
Summary  : Versatile Linux deployment server
---

=== dnf module info module

*Example:*

=== dnf module info --profile module:stream

*Example:*

=== dnf module list

`dnf module list <module_name>`

*Example:*

== General dnf Commands

TO BE PROVIDED

=== dnf search 

`dnf search <string>`

*Example:*

=== dnf install

`dnf install <package_name>`

*Example:*

=== dnf update

`dnf update <package_name>`

=== dnf remove

`dnf remove <package_name>`

*Example:*

=== dnf history undo last

`sudo dnf history undo last`

*Example:*

=== dnf list all

*Example:*

=== dnf list installed

*Example:*

=== dnf repolist

*Example:*

== Subscription Commands

TO BE PROVIDED

=== subscription-manager repos --enable repository

*Example:*

=== subscription-manager repos --disable repository

*Example:*

== General Module Commands

=== dnf module enable module:stream

*Example:*

=== dnf module install module:stream/profile

*Example:*

=== dnf module remove module

*Example:*

=== dnf module disable module

*Example:*

== Application Stream Commands

=== sudo dnf install

*Examples:*

The following are application and module specific examples of using the command `dnf install`. Notice that the commands are run with administrator privileges using the `sudo` command.

`sudo dnf install ant`

`sudo dnf install buildah podman`

`sudo dnf install llvm-toolset`

`sudo dnf group install "Development Tools"`

`sudo dnf install go-toolset`

`sudo dnf install httpd`

`sudo dnf install mariadb`

`sudo dnf install maven`

`sudo dnf install mysql`

`sudo dnf install nginx`

`sudo dnf install nodejs`

`sudo dnf install java-11-openjdk-devel`

`sudo dnf install java-1.8.0-openjdk-devel`

`sudo dnf install pcp-zeroconf`

`sudo dnf install perl`

`sudo dnf install php`

`sudo dnf install postgresql`

`sudo dnf module install postgresql:9.6`

`sudo dnf install python2 or dnf module install python27`

`sudo dnf install python3 or dnf module install python36`

`sudo dnf install redis`

`sudo dnf install ruby`

`sudo dnf install rust-toolset`

`sudo dnf install scala`

`sudo dnf install subversion`

`sudo dnf install swig`

`sudo dnf install systemtap`

`sudo dnf install valgrind`

`sudo dnf install varnish`