= Podman Cheat Sheet
:experimental: true
:product-name:

This cheat sheet covers the command used for working with Podman.

As stated by Podman.io, _Podman is a daemonless, open source, Linux native tool designed to make it easy to find, run, build, share and deploy applications using Open Containers Initiative (OCI) Containers and Container Images._

As stated above, Podman is daemonless. This means the Podman interacts directly with the various components in the Linux container ecosystem instead of relying on a continuously running daemon to intermediate between these components on a callers behalf. Podman does not run as root by default which reduces the potential for a security hazard.

Also, Podman does *not* spawn containers as child processes thus making the containers it creates durable and independent of Podman.

== Working with image repositories

The following sections describe the Podman commands for working with image repositories.

=== podman images

----
podman images
----

Lists all local images

*Example:*

The following example lists all the container images stored on the local machine. Notice that the local machine has container images from two public container image repositories, `quay.io` and `docker.io`. (The `$` symbol represents the command line prompt.)

----
$ podman images
REPOSITORY                      TAG         IMAGE ID      CREATED       SIZE
quay.io/ansible/ansible-runner  latest      697a4af2d624  16 hours ago  738 MB
docker.io/library/mysql         latest      6126b4587b1b  18 hours ago  525 MB
docker.io/library/redis         latest      f1b6973564e9  4 weeks ago   116 MB
docker.io/library/nginx         latest      c316d5a335a5  4 weeks ago   146 MB
----

=== podman history 

----
podman history <image:tag>
----

Displays historical information about a container image that has been download and stored on the local machine

*Example:*

The following example is an excerpt of output from using `podman history` to get the historical information for the container image the distributed tracing framework `zipkin` that was retrieved from the container image repository `quay.io`.

----
$ podman history quay.io/openzipkin/zipkin:latest
ID            CREATED       CREATED BY                                     SIZE        COMMENT
b9fb334d7cd1  2 years ago   /busybox/sh -c #(nop)  ENTRYPOINT ["/busyb...  0 B         
<missing>     2 years ago   /busybox/sh -c #(nop)  EXPOSE 9410 9411        0 B         
<missing>     2 years ago   /busybox/sh -c #(nop)  USER zipkin             0 B         
<missing>     2 years ago   /busybox/sh -c ln -s /busybox/* /bin           197 kB      
<missing>     2 years ago   /busybox/sh -c #(nop) WORKDIR /zipkin          0 B         
.
.
.
----

=== podman login

----
podman login <image_registry_url>
----

Logs a user in to a remote container image registry. After executing the command, the user will be prompted for a username and password

*Example:*

The following example uses `podman login` to login to the container image repository `quay.io`. Notice that after the command prompts for a Username and Password pair.

----
$ podman login quay.io
Username: cooluser
Password: 
Login Succeeded!
----

=== podman pull

----
podman pull <remote_registry_url>/<username>/<image:tag>
----

Pulls an image from a remote registry

*Example:*

The following example demonstrates how to `podman pull` to retrieve the latest version of the container image for the tool `ansible-runner` from the container image repository at quay.io. 

----
$  podman pull quay.io/ansible/ansible-runner:latest
----

=== podman search
----
podman search <search_string>
----

Will search container image registries according to those defined in the file `/etc/containers/registries.conf`. The following shows the entries in `/etc/containers/registries.conf` for defining the container image registries  to search.

----
[registries.search]
registries = ["quay.io", "registry.fedoraproject.org", "registry.access.redhat.com", "registry.centos.org", "docker.io"]
----

*Example:*

The following example uses `podman search` to find container image include the string `pinger`. The response in displayed in an abbreviated format.

----
$ podman search pinger
INDEX       NAME                                    DESCRIPTION                                      STARS       OFFICIAL    AUTOMATED
quay.io     quay.io/giantswarm/calico-ipip-pinger                                                    0                       
quay.io     quay.io/dontpayfull/calico-ipip-pinger                                                   0                       
quay.io     quay.io/zonggen/fcos-pinger-backend     Server image for telemetry service of FCOS (...  0                       
quay.io     quay.io/fredriksvensson/pinger                                                           0                       
quay.io     quay.io/marian/pinger                                                                    0                       
quay.io     quay.io/latchmihay/edge-pinger          Small utility that pings a list or domain na...  0                       
quay.io     quay.io/jdzon/pinger                                                                     0                       
quay.io     quay.io/ksemaev/pinger                                                                   0                       
quay.io     quay.io/murph83/pinger                                                                   0                       
quay.io     quay.io/sosivio/sosivio-node-pinger                                                      0                       
quay.io     quay.io/sebv/pinger                                                                      0                       
docker.io   docker.io/hosterping/pinger             Pinger v2 für Hoster-Ping.de                     0                       
docker.io   docker.io/nefilim/pinger                Simple network monitor based on latency chec...  1                       
docker.io   docker.io/dariob/pinger-alpine                                                           0                       
docker.io   docker.io/dariob/pinger-nano-1809                                                        0                       
docker.io   docker.io/appcelerator/pinger           Simple service that sends a pong response        0                       [OK]
docker.io   docker.io/clambin/pinger                Measures the latency and packet loss to one ...  0                       
docker.io   docker.io/afrank/pinger                                                                  0                       
docker.io   docker.io/subfuzion/pinger              Simple service that sends a pong response        0                       
docker.io   docker.io/pingerua/samples                                                               0                       
docker.io   docker.io/superbrilliant/pinger                                                          0                       
docker.io   docker.io/reselbob/pinger               A simple utility web server image that outpu...  1                       
----

=== podman logout

----
podman logout
----

Logs out of the current container registry

*Example:*

----
TO BE PROVIDED
----


== Building images

The following sections describe the various Podman commands for building container images

=== podman build

----
podman build -t <image:tag_> -f <Dockerfile_filepath_or_url>
----

Builds and tags an image using the instructions in Dockerfile. The location of the Dockerfile is defined by the `-f` option. If the `-f` option is omitted, use a period (`.`) to indicate that the Dockerfile is in the current directory.

*Examples:*

The following example demonstrates how to use `podman build`` to create a container image using the Dockerfile in the local directory

----
TO BE PROVIDED
----

The following example demonstrates how to use `podman build`` to create a container image using the file named `mydockerfile`

----
TO BE PROVIDED
----

=== podman tag

----
podman tag <image:tag> <remote_registry_url>/<username>/<image:tag>
----

Tags an image

*Example:*

----
TO BE PROVIDED
----


== Working with containers

The following sections describe the Podman commands for creating and running containers

=== podman run

----
podman run [options] <image:tag>
----

Runs a container based on a given image.

*Examples:*

EXPLANATION TO BE PROVIDED

----
podman run nginx:latest
----


Creates and runs the container and uses the `--name` option to give the container the name `mywebserver`.

----
podman run --name mywebserver -it nginx:latest
----

Creates and runs the container. The option `--rm` makes it so that the container is removed after it exits

----
podman run --rm nginx:latest
----

Creates and runs the container. The option `-it` makes it so a terminal and command prompt within the container is presented after the container gets up and running.

----
podman run -it nginx:latest 
----

Creates and runs the container using the `nginx:latest` image. Then after the container is up and running, the command `pwd` is executed against file system internal to the container to report present working directory. The symbol `$` represents the command line prompt. The result of the running the command follows.

----
$ podman run nginx:latest pwd
/
----

=== podman stop

----
podman stop <container_name_or_container_uuid>
----

Gracefully stops a container from running.

*Example:*

----
TO BE PROVIDED
----

=== podman start

----
podman start <container_name_or_container_uuid>
----

Starts an existing container

*Example:*

----
TO BE PROVIDED
----

=== podman create

----
podman create <container_name_or_container_uuid>
----

Creates a container from a container image but does not start it

*Example:*

----
TO BE PROVIDED
----

=== podman restart

----
podman restart <container_name_or_container_uuid>
----

Restarts an existing container

*Example:*

----
TO BE PROVIDED
----

=== podman rm

----
podman rm <container_name_or_container_uuid>
----

Removes a container from memory

*Example:*

----
TO BE PROVIDED
----

=== podman rm

----
podman rm <container_name_or_container_uuid>
----

 Removes a container from memory. Use `-f` if the container is running.

*Example:*

----
TO BE PROVIDED
----

=== podman wait

----
podman wait <container_to_wait_for>
----

Waits for a the container defined by `<container_to_wait_for>` to stop.

*Example:*

----
TO BE PROVIDED
----

=== podman stats

----
podman stats <container_name_or_container_uuid>
----

Displays a live stream of a container's resource usage (or all containers)

*Example:*

----
TO BE PROVIDED
----

=== podman inspect

----
podman inspect <container_name_or_container_uuid>
----

Returns metadata (in JSON) describing a running container 

*Example:*

----
TO BE PROVIDED
----


== Working with container processes and resources

The following sections describe the various Podman commands for working with containers and container images beyond creating, running and stopping containers.

=== podman ps

----
podman ps [options]
----

Lists the containers on the system

*Example:*

----
TO BE PROVIDED
----

=== podman commit 

----
podman commit <<container_name_or_container_uuid> <new_image_name:tag_name>
----

Creates a new image based on the current state of a running container

*Example:*

----
TO BE PROVIDED
----

=== podman attach

----
podman attach <container_name_or_container_uuid> <new_image_name:tag_name>
----

Attaches to a running container and views its output or control it + 
kbd:[Ctrl+p] kbd:[Ctrl+q] detaches from the container but leaves it running. 

*Example:*

----
TO BE PROVIDED
----

=== podman exec

----
podman exec <container_name_or_container_uuid> <command>
----

Executes a command in a running container 

*Example:*

----
TO BE PROVIDED
----

=== podman top

----
podman top <container_name_or_container_uuid>
----

Displays the running processes of a container 

*Example:*

----
TO BE PROVIDED
----

=== podman logs

----
podman logs [options] <container_name_or_container_uuid>
----

Displays the logs of a container as defined by `<container_name_or_container_uuid>`

*Example:*

----
$ podman logs -tail mynginx

MORE TO COME
----

=== podman pause

----
podman pause [options] <container_name_or_container_uuid>
----

Pauses all the processes in a container (or all containers)

*Example:*

----
TO BE PROVIDED
----

=== podman unpause

----
podman unpause [options] <container_name_or_container_uuid>
----

Unpauses all processes in a container (or all containers) 

*Example:*

----
TO BE PROVIDED
----

=== podman port

----
podman port [options] <container_name_or_container_uuid>
----

Lists the port mappings from a container to localhost 

*Example:*

----
TO BE PROVIDED
----

== Working with a container's filesystem

The sections describe the Podman commands for working a containers in terms of the host computers file system.

=== podman diff

----
podman diff [options] <container_name_or_container_uuid>
----

Displays all the changes to a container’s filesystem

*Example:*

----
TO BE PROVIDED
----

=== podman diff

----
podman diff [options] <container_name_or_container_uuid>
----

Displays all the changes to a container's filesystem

*Example:*

----
TO BE PROVIDED
----

=== podman mount

----
podman mount [options] <container_name_or_container_uuid>
----

Mounts a container's root filesystem


*Copy files and folders between a container and localhost:*

Use `podman mount`, copy files with `cp` or any Linux tool you like (`tar` or `dnf`, for example), then use `podman umount`

*Example:*

----
TO BE PROVIDED
----

=== podman umount

----
podman umount [options] <container_name_or_container_uuid>
----

Unmounts a container's root filesystem

*Example:*

----
TO BE PROVIDED
----

=== podman import

----
podman import <tarball_filename>
----

Imports a tarball as defined by the parameter <tarball_filename> and saves it as a filesystem image

*Example:*

----
TO BE PROVIDED
----

=== podman export

----
podman export -o <output_filename> <container_name_or_container_uuid>
----

Exports a container's filesystem to a `.tar` file

*Example:*

----
TO BE PROVIDED
----

=== podman save

----
podman export <container_image:tag> -o <archive_filename> --format <docker-archive> or <oci-archive> or <oci-dir> or <docker-dir> 
----

Saves a container image in `docker-archive` format (default) or another format

*Example:*

----
TO BE PROVIDED
----

=== podman load

----
podman load -i <archive_path_and_filename>
----

Loads a saved image from `docker-archive` or an image in another format 

*Example:*

----
TO BE PROVIDED
----

== Sharing container images

TO BE PROVIDED


=== podman push

----
podman push <registry_url/username/image:tag>
----

Pushes a container image to a remote registry

*Example:*

----
TO BE PROVIDED
----

=== podman rmi

----
podman rmi [-f] <container_image_name_or_image_uuid:tag>
----

Removes a local image from local cache. Use `-f`` to force removal. 

*NOTE:* This command does not remove the image from the remote registry. 

*Example:*

----
$ podman rmi [-f] c316d5a335a5 
----


== Miscellaneous
TO BE PROVIDED

=== podman version

----
podman version 
----

Reports the installed version of Podman

*Example:*

----
TO BE PROVIDED
----

=== podman info

----
podman info 
----

Displays information about the podman environment

*Example:*

----
TO BE PROVIDED
----
 
