= git Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

== Git operational overview

`INTRODUCTION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

{empty}[Working Directory] → (add) → [Staging] → (commit) → [Local Repo] → (push) → [Remote Repo]

=== Creating and updating content

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== Adding content to Staging
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== Committing content to the local repository
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== Pushing content to the remote repository
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Creating a repository

`INTRODUCTION TO BE PROVIDED`

=== git clone

Downloads content from a remote repository for local operations

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git init

Creates a local repository

*Example:*

`EXAMPLE TO BE PROVIDED`


== Managing a repository

`INTRODUCTION TO BE PROVIDED`

=== git remote

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git remote add

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git status

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git diff

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git add

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git commit

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git reset

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git revert

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git fetch

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git push

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git pull

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Merging and rebasing files

`INTRODUCTION TO BE PROVIDED`

=== git merge

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git mergetool

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git rebase

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Viewing history of files in a repository

`INTRODUCTION TO BE PROVIDED`

=== git log

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git blame

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Branch, commit and tag management

`INTRODUCTION TO BE PROVIDED`

=== git branch

Displays the various branches within a repository

----
git branch [options]
----

*Example:*

The following example uses the `-a` to list the all the branches in the local repository and shows the result. (`$` is the symbol for the command line prompt.)
----
$  git branch -a
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/feature/add_autocomplete
  remotes/origin/feature/add_help
  remotes/origin/main
----


=== git checkout

Checks out files from a branch in the local repository.

*Example:*

The following example checks out the files in the branch `feature/add_help` from the local repository and makes those files available in the working branch.

----
$ git checkout feature/add_help
Branch 'feature/add_help' set up to track remote branch 'feature/add_help' from 'origin'.
Switched to a new branch 'feature/add_help'
----

=== git tag

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Merging and rebasing

`INTRODUCTION TO BE PROVIDED`

=== git merge
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git mergetool
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git rebase
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Conflict resolution

`INTRODUCTION TO BE PROVIDED`

CONFLICT RESOLUTION SUBHEADS TO BE PROVIDED









