= git Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

== Git operational overview

`INTRODUCTION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

{empty}[Working Directory] → (add) → [Staging] → (commit) → [Local Repo] → (push) → [Remote Repo]

== Working with repositories

`INTRODUCTION TO BE PROVIDED`

=== git clone

Downloads content from a remote repository for local operations

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git init

Creates a local repository

*Example:*

`EXAMPLE TO BE PROVIDED`

----
git init
----

=== git pull

Downloads the latest, current assets from the remote repository

----
git pull [options] <repository>
----

`INTRODUCTION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git fetch

----
git fetch options] <repository>
----

`INTRODUCTION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Working with branches

`INTRODUCTION TO BE PROVIDED`

=== Viewing existing remote branches

----
git branch -r
----

Displays the branches on the remote repository

*Example:*

----
$ git branch -r
  origin/HEAD -> origin/master
  origin/master
----

=== Viewing all branches
----
git branch -a
----

Displays all branches both on the local and remote repositories

*Example:*
The following example displays all branches, local and remote, for the repository associated with the current working directory. Notice that the symbol `*` indicates the current working branch, in this case `* main`.

----
$ git branch -a
  dev
* main
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
----

=== Creating a branch in the local repository

----
git branch <new_branch_name> <existing_tag_name>
----

*Example:*

The following example creates the a branch named `dev` that has the directories and files from the existing branch named `main`.

----
git branch dev main
----

=== Changing branches

----
git checkout <branch_name>
----

*Example:*

The following example changes the current working branch to the branch named `dev`. Then the command `git branch` is called to verify the branch change. Notice that the symbol `*` indicates the current working branch, in this case `* dev`.

----
$ git checkout dev
Switched to branch 'dev'

$ git branch 
* dev
  master
$ 
----

== Working with content

=== Adding new or updated content to Staging
----
git add [options] <files or directories>
----

Adds content to the Staging area according to the current branch in the local repository.

*Example:*

The following example creates a directory named `git_cheat_sheet` in the current branch. Then a file named `readme.md` is added to directory named `git_cheat_sheet`. Finally the `git add` command is used to add the local git Staging environment.

----
$ mkdir git_cheat_sheet
$ touch ./git_cheat_sheet/readme.md
$ git add ./git_cheat_sheet/
----

=== Committing new or updated content to the local repository

----
git commit [options] <files or directories>
----

Commits content to the local repository

*Example:*

The  following example uses the `git commit` command to commit the file `./git_cheat_sheet/readme.md` to the local repository along with a descriptive message: `adding new file for git-cheat-sheet`.

----
$ git commit -m "adding new file for git-cheat-sheet" ./git_cheat_sheet/readme.md
[dev 0c0fb31] adding content for git-cheat-sheet
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 git_cheat_sheet/readme.md
----

=== Pushing new or updated content to the remote repository

----
git push [options] <remote_repository>
----

Uploads content from the local repository to the remote repository. The parameter `<remote_repository>` is optional. If no remote repository is defined, content is pushed to the repository associated with the current working directory.

*Example:*

The following example uploads all content committed to the local repository up the default remote repository associated with the current working directory.

----
git push
----

=== Rolling back to a previous version

----
git reset
----

----
git reverts
----

*Example:*

`EXAMPLE TO BE PROVIDED`

== Merging content between branches

=== git merge

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git mergetool

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git rebase

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Viewing history of files in a repository

`INTRODUCTION TO BE PROVIDED`

=== git log

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git blame

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Branch, commit and tag management

`INTRODUCTION TO BE PROVIDED`

=== git branch

Displays the various branches within a repository

----
git branch [options]
----

*Example:*

The following example uses the `-a` to list the all the branches in the local repository and shows the result. (`$` is the symbol for the command line prompt.)
----
$  git branch -a
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/feature/add_autocomplete
  remotes/origin/feature/add_help
  remotes/origin/main
----


=== git checkout

Checks out files from a branch in the local repository.

*Example:*

The following example checks out the files in the branch `feature/add_help` from the local repository and makes those files available in the working branch.

----
$ git checkout feature/add_help
Branch 'feature/add_help' set up to track remote branch 'feature/add_help' from 'origin'.
Switched to a new branch 'feature/add_help'
----

=== git tag

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Merging and rebasing

`INTRODUCTION TO BE PROVIDED`

=== git merge
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git mergetool
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git rebase
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Conflict resolution

`INTRODUCTION TO BE PROVIDED`

CONFLICT RESOLUTION SUBHEADS TO BE PROVIDED









