= git Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

== Git operational overview

Working with `git` source control management requires understanding conceptual structures for managing content flow to and from a `git` repository. According to `git` the source of truth is the independent remote `git` repository. A remote repository can be hosted on a private network or by a public service such as GitHub or BitBucket.

Moving content to and from the remote repository happens in a formal manner. Under `git` there are four locations in which source control activities take place. These locations are

* Working directory
* Staging environment
* Local repository
* Remote repository

The sections that follow describe the purpose and use of each location.

=== Working directory

The working directory is the location in the file system of the local computer in which the `.git` file is stored. The `.git` file is the physical representation of the local repository. Developer make changes to code in the working directory.

=== Staging environment

The Staging environment is an area that is special to `git`. Developers use the `git add` and `get reset` commands to add files to and remove files from the Staging environment. You can think of Staging as the temporary area where file are stored before being committed to the local repository.

=== Local repository
The local repository is the instance of the git repository stored on the local computer. The physical representation of the local repository is the `.git` file. Once content has been added to the Staging environment, developers use the `git commit` to store new and updated content to the local repository. 

The local repository is updated from the remote repository using the `git pull` command.

=== Remote repository

The remote repository is the `git` repository on the network that is the single source of truth for all content being managed under a particular `git` repository. Developers use the `git push` to upload content from the local repository to a remote repository.

Content in the remote repository can be versioned using branches. The root branch is typically named `main`.


*Example:*

The following example shows the Working Directory, Staging Environment, Local Repository and Remote Repository locations along with the `git` commands to move data to and from each location. Once content has been pulled from a remote repository to a local repository, that content is available in the local filesystem according to the given branch.

----
[Working Directory] → (add) → [Staging] → (commit) → [Local Repo] → (push) → [Remote Repo]
                                                        ↑  ←  ←  ←  (pull)  ←   ←  ↲ 
----

== Working with repositories

The following sections describe `git` commands to create a local repository, download (clone) a remote repository to a local machine, and update a local repository with changes from a remote repository.

=== git init

----
git [options] init <repo_directory>
----

Creates a local repository as represented by the file `.git`. If the optional parameter `<repo_directory>` is not provided, the `.git` file is created in the current directory. If the parameter `<repo_directory>` is provided, that directory is created and the `.git` file is created in that directory.


*Example:*

The following example uses the `git init` command to create a local repository in the `/home` directory of the user `lennonjohn`. The example creates the directory `coolcode` as the repository directory in which the repository `.git` file is stored.

----
$ git init ./coolcode
Initialized empty Git repository in /home/lennonjohn/coolcode/.git/
----

=== git clone

----
git clone [options] <remote_repo_url> <target_directory>
----

Downloads content from a remote repository for local operations. If the parameter `<target_directory>` is provided, the repository contents will be downloaded into that directory. (That directory must be empty.) Otherwise, `git` will create a directory based on the remote repository name.
 
*Example:*

The following example uses the command `git clone` to download the content of the remote repository found at `https://github.com/redhat-developer/developers.redhat.com` into the local directory `./rh`.

----
git clone https://github.com/redhat-developer/developers.redhat.com.git ./rh
----

=== git pull

Calling the `git pull` from a directory of a local repository downloads the latest, current assets from the associated remote repository.

----
git pull [options]
----

*Example:*

The following example uses `git pull` to download files from the associated remote repository. Since contents in the remote repository and local repository are the same, the command responds with a message `Already up to date.`.

----
$ git pull
Already up to date.
----

=== git fetch

----
git fetch [options] <repository>
----

Downloads code and assets from the remote repository to the local machine without overwriting the existing local code and assets in the current branch.

*Example:*

`EXPLANATION TO BE PROVIDED`

----
git fetch
----



== Working with branches

`INTRODUCTION TO BE PROVIDED`

=== Viewing existing remote branches

----
git branch -r
----

Displays the branches on the remote repository

*Example:*

----
$ git branch -r
  origin/HEAD -> origin/main
  origin/main
----

=== Viewing all branches
----
git branch -a
----

Displays all branches both on the local and remote repositories

*Example:*
The following example displays all branches, local and remote, for the repository associated with the current working directory. Notice that the symbol `\*` indicates the current working branch, in this case `* main`. (`$` is the command-prompt symbol)

----
$ git branch -a
  dev
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/main
----

=== Creating a branch in the local repository

----
git branch <new_branch_name> <existing_branch_name>
----

Creates a new branch. If the optional parameter `<existing_branch_name>` is not provided, the new branch is derived from the current working branch.

*Example:*

The following example creates the a branch named `dev` that has the directories and files from the existing branch named `main`.

----
git branch dev main
----

=== Changing branches

----
git checkout <branch_name>
----

*Example:*

The following example changes the current working branch to the branch named `dev`. Then the command `git branch` is called to verify the branch change. Notice that the symbol `*` indicates the current working branch, in this case `* dev`.

----
$ git checkout dev
Switched to branch 'dev'

$ git branch 
* dev
  main
----

== Working with content

=== Determining the status of the local filesystem

----
git status [options] <directory_or_filename>
----

Reports the status of the current filesystem associated with the local repository. The parameter `<directory_or_filename>` is optional. If no `<directory_or_filename>` is provided, status is reported according to the present working directory (`pwd0`).

*Example:*

The following example uses `git status` to report the status of file and directories in the present working directory in comparison the state of the local repository.

----
$ git status
On branch dev
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   git_cheat_sheet/readme.md

no changes added to commit (use "git add" and/or "git commit -a")
----


=== Adding new or updated content to Staging
----
git add [options] <files or directories>
----

Adds content to the Staging area according to the current branch in the local repository.

*Example:*

The following example creates a directory named `git_cheat_sheet` in the current branch. Then a file named `readme.md` is added to directory named `git_cheat_sheet`. Finally the `git add` command is used to add the local git Staging environment.

----
$ mkdir git_cheat_sheet
$ touch ./git_cheat_sheet/readme.md
$ git add ./git_cheat_sheet/
----

=== Committing new or updated content to the local repository

----
git commit [options] <files or directories>
----

Commits content to the local repository

*Example:*

The  following example uses the `git commit` command to commit the file `./git_cheat_sheet/readme.md` to the local repository along with a descriptive message: `adding new file for git-cheat-sheet`.

----
$ git commit -m "adding new file for git-cheat-sheet" ./git_cheat_sheet/readme.md
[dev 0c0fb31] adding content for git-cheat-sheet
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 git_cheat_sheet/readme.md
----

=== Pushing new or updated content to the remote repository

----
git push [options] <remote_repository>
----

Uploads content from the local repository to the remote repository. The parameter `<remote_repository>` is optional. If no remote repository is defined, content is pushed to the repository associated with the current working directory.

*Example:*

The following example uploads all content committed to the local repository up the default remote repository associated with the current working directory.

----
git push
----

=== Rolling back to a previous version

----
git restore
----

----
git reset
----

----
git reverts
----

*Example:*

`EXAMPLE TO BE PROVIDED`

== Merging content between branches

=== git merge

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git mergetool

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git rebase

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Viewing history of files in a repository

`INTRODUCTION TO BE PROVIDED`

=== git log

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git blame

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Branch, commit and tag management

`INTRODUCTION TO BE PROVIDED`

=== git branch

Displays the various branches within a repository

----
git branch [options]
----

*Example:*

The following example uses the `-a` to list the all the branches in the local repository and shows the result. (`$` is the symbol for the command line prompt.)
----
$  git branch -a
* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/feature/add_autocomplete
  remotes/origin/feature/add_help
  remotes/origin/main
----


=== git checkout

Checks out files from a branch in the local repository.

*Example:*

The following example checks out the files in the branch `feature/add_help` from the local repository and makes those files available in the working branch.

----
$ git checkout feature/add_help
Branch 'feature/add_help' set up to track remote branch 'feature/add_help' from 'origin'.
Switched to a new branch 'feature/add_help'
----

=== git tag

`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Merging and rebasing

`INTRODUCTION TO BE PROVIDED`

=== git merge
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git mergetool
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

=== git rebase
`EXPLANATION TO BE PROVIDED`

*Example:*

`EXAMPLE TO BE PROVIDED`

== Conflict resolution

`INTRODUCTION TO BE PROVIDED`

CONFLICT RESOLUTION SUBHEADS TO BE PROVIDED









