= systemd Commands Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

This cheat sheet presents a list of command-line executables that are used for working with `systemd``. The purpose of `systemd`` is to consolidate service configuration and application behavior.

`systemd`` is found in Red Hat Enterprise Linux as well as other Linux distributions. 

== Application management systemctl commands

`systemctl` is the application that interacts with systemd from the command line. The following commands demonstrate how to use various `systemctl` subcommands to control the behavior of a particular services running on a computer. 

=== systemctl enable

`systemctl [options] enable <service_name>`

Enables a service. Enabling a service makes it so the service will startup upon reboot or whenever a computer starts up. The `enable` does not start the particular service. However, the service will restart upon reboot. To start a service using `systemctl` use the command set `systemctl start`.

*Example:*

The following example invokes the `systemctl enable` to configure the `sshd` secure shell service to invoke at system startup. Then, the command set `systemctl is-enabled` is invoked to verify that the `sshd` services is enabled.

The `systemctl enable` command set requires administrator permissions to execute. The command set can be run as `sudo`. If `sudo` is not used, the `systemctl enable` command set will prompt for the administrator password.

```
sudo systemctl enable sshd

$ systemctl is-enabled sshd
enabled
```

=== systemctl restart

`systemctl [options] restart <service_name>`

Restarts a service.

The `systemctl restart` command set requires administrator permissions to execute. The command set can be run as `sudo`. If `sudo` is not used, the `systemctl restart` command set will prompt for the administrator password.

*Example:*

The following example uses the `systemctl restart` command set to restart the `httpd` web server.

```
$ sudo systemctl restart httpd
```

=== systemctl start

`systemctl [options] start <service_name>`

Starts a service.

The `systemctl start` command set requires administrator permissions to execute. The command set can be run as `sudo`. If `sudo` is not used, the `systemctl start` command set will prompt for the administrator password.

*Example:*

The following example uses the `systemctl start` command set to start the `httpd` web server. Then, the command set `systemctl status httpd` is called to verify that the `httpd` service is running. Notice that calling `systemctl status` does not require administrator permissions.

```
$ sudo systemctl start httpd

$ systemctl status httpd
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-01-24 09:31:10 PST; 2s ago
     Docs: man:httpd.service(8)
 Main PID: 41263 (httpd)
   Status: "Started, listening on: port 80"
    Tasks: 213 (limit: 49364)
   Memory: 36.7M
   CGroup: /system.slice/httpd.service
           ├─41263 /usr/sbin/httpd -DFOREGROUND
           ├─41264 /usr/sbin/httpd -DFOREGROUND
           ├─41265 /usr/sbin/httpd -DFOREGROUND
           ├─41266 /usr/sbin/httpd -DFOREGROUND
           └─41267 /usr/sbin/httpd -DFOREGROUND

Jan 24 09:31:09 localhost.localdomain systemd[1]: Starting The Apache HTTP Server...
Jan 24 09:31:10 localhost.localdomain httpd[41263]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, us>
Jan 24 09:31:10 localhost.localdomain systemd[1]: Started The Apache HTTP Server.
Jan 24 09:31:10 localhost.localdomain httpd[41263]: Server configured, listening on: port 80
```

=== systemctl status

`systemctl [options] status <service_name>`

Reports status information about a service.

*Example:*

The following example uses the `systemctl status` to report status information about the `sshd` service. `systemctl status` also displays log information about the service's activities via log entries that follow the status information.

```
$ systemctl status sshd
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2022-01-21 10:13:49 PST; 2 days ago
     Docs: man:sshd(8)
           man:sshd_config(5)
 Main PID: 1026 (sshd)
    Tasks: 1 (limit: 49364)
   Memory: 4.5M
   CGroup: /system.slice/sshd.service
           └─1026 /usr/sbin/sshd -D -oCiphers=aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes256-cbc,aes128-gcm@openssh.c>

Jan 21 10:13:49 localhost.localdomain systemd[1]: Starting OpenSSH server daemon...
Jan 21 10:13:49 localhost.localdomain sshd[1026]: Server listening on 0.0.0.0 port 22.
Jan 21 10:13:49 localhost.localdomain sshd[1026]: Server listening on :: port 22.
Jan 21 10:13:49 localhost.localdomain systemd[1]: Started OpenSSH server daemon.
Jan 21 10:23:25 localhost.localdomain sshd[2136]: Accepted password for reselbob from 192.168.86.20 port 59909 ssh2
Jan 21 10:23:25 localhost.localdomain sshd[2136]: pam_unix(sshd:session): session opened for user reselbob by (uid=0)
Jan 24 08:42:43 localhost.localdomain sshd[40279]: Accepted password for reselbob from 192.168.86.20 port 61945 ssh2
Jan 24 08:42:43 localhost.localdomain sshd[40279]: pam_unix(sshd:session): session opened for user reselbob by (uid=0)
lines 1-19/19 (END)
```

=== systemctl stop

`systemctl [options] stop <service_name>`

Stops a service. The `systemctl stop` command set requires administrator permissions to execute. The command set can be run as `sudo`. If `sudo` is not used, the `systemctl stop` command set will prompt for the administrator password.

*Example:*

The following example uses the `systemctl stop` command set to stop the `httpd` service. Then the `systemctl status httpd` is called to report the status. Notice that the line:

`Active: inactive (dead) since Mon 2022-01-24 09:56:53 PST; 3s ago`

in the status output reports that the `httpd` service is inactive.

```
$ systemctl stop httpd

$ systemctl status httpd
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mon 2022-01-24 09:56:53 PST; 3s ago
     Docs: man:httpd.service(8)
  Process: 1262 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=exited, status=0/SUCCESS)
 Main PID: 1262 (code=exited, status=0/SUCCESS)
   Status: "Running, listening on: port 80"

Jan 24 09:32:27 localhost.localdomain systemd[1]: Starting The Apache HTTP Server...
Jan 24 09:32:34 localhost.localdomain httpd[1262]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, usi>
Jan 24 09:41:29 localhost.localdomain systemd[1]: Started The Apache HTTP Server.
Jan 24 09:41:29 localhost.localdomain httpd[1262]: Server configured, listening on: port 80
Jan 24 09:56:52 localhost.localdomain systemd[1]: Stopping The Apache HTTP Server...
Jan 24 09:56:53 localhost.localdomain systemd[1]: httpd.service: Succeeded.
Jan 24 09:56:53 localhost.localdomain systemd[1]: Stopped The Apache HTTP Server.
```

== Computer control commands

The following commands use the `systemctl` subcommands to reboot and shutdown a computer.

=== systemctl poweroff

`systemctl [options] poweroff`

Shuts down the computer or virtual machine.

The command requires that user invoking it have administrator permission. Thus the command must be invoked using `sudo`. If `sudo` in not used, `systemctl` prompts for the user's password.

*Example:*

```
sudo systemctl poweroff
```

=== systemctl reboot

`systemctl [options] reboot`

*Example:*

The following example reboots the computer or virtual machine using the `-i` option to ignore users logged in and open inhibitors .

The command requires that user invoking it have administrator permission. Thus the command must be invoked using `sudo`. If `sudo` in not used, `systemctl` prompts for the user's password.

```
sudo systemctl -i reboot
```

== System information commands

The following shows how to use the `journalctl` and `systemctl` programs to get information about services running under `systemd.`

=== journalctl

`journalctl [options]`

`journalctl`  is the tool used to work with systemd logging capabilities. `systemd` stores the system, boot, and kernel log files in a central location, in a binary format.  `journalctl` presents information in the central logging system in human readable text.

*Example:*

```
$ journalctl --follow
-- Logs begin at Mon 2022-01-24 09:31:39 PST. --
Jan 24 10:01:20 localhost.localdomain systemd[1]: Starting The Apache HTTP Server...
Jan 24 10:01:20 localhost.localdomain httpd[2813]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
Jan 24 10:01:20 localhost.localdomain systemd[1]: Started The Apache HTTP Server.
Jan 24 10:01:20 localhost.localdomain polkitd[876]: Unregistered Authentication Agent for unix-process:2787:124099 (system bus name :1.333, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Jan 24 10:01:20 localhost.localdomain httpd[2813]: Server configured, listening on: port 80
Jan 24 10:03:29 localhost.localdomain systemd[1]: Starting dnf makecache...
Jan 24 10:03:34 localhost.localdomain dnf[3052]: Updating Subscription Management repositories.
Jan 24 10:03:35 localhost.localdomain dnf[3052]: Metadata cache refreshed recently.
Jan 24 10:03:35 localhost.localdomain systemd[1]: dnf-makecache.service: Succeeded.
Jan 24 10:03:35 localhost.localdomain systemd[1]: Started dnf makecache.
```

=== systemctl list-sockets

`systemctl [options] list-sockets <unit_name_pattern>`

Lists the sockets in memory available for inter-process communication (IPC).

*Example:*

The following example lists the sockets in memory using the pattern `systemd*` to show only those sockets that have a unit name that begins with the characters `systemd`. Also, the option `--show-types` is used to display the `TYPE` column in the output.

```
$ systemctl --show-types list-sockets 'systemd*' 
LISTEN                       TYPE             UNIT                            ACTIVATES
/run/initctl                 FIFO             systemd-initctl.socket          systemd-initctl.service
/run/systemd/coredump        SequentialPacket systemd-coredump.socket         systemd-coredump@0.service
/run/systemd/journal/dev-log Datagram         systemd-journald-dev-log.socket systemd-journald.service
/run/systemd/journal/socket  Datagram         systemd-journald.socket         systemd-journald.service
/run/systemd/journal/stdout  Stream           systemd-journald.socket         systemd-journald.service
/run/udev/control            SequentialPacket systemd-udevd-control.socket    systemd-udevd.service
kobject-uevent 1             Netlink          systemd-udevd-kernel.socket     systemd-udevd.service

7 sockets listed.
Pass --all to see loaded but inactive sockets, too.
```
=== systemctl list-units

`systemctl [options] list-units <pattern>`

List units that `systemd` has in memory. Units are listed with the following columns:

*  `UNIT` – the name of the unit
* `LOAD` – indicates if the unit is loaded or not
* `ACTIVE` – indicates if the unit is active or not
* `SUB` – indicates low-level activation state, for example: `mounted` or `running`
* `DESCRIPTION` – describes the service or unit

A unit refers to any resource that systemd knows how to operate on and manage.

*Example:*

The following example uses the `systemctl list-units` command set to list units in memory. The pattern `sys-k*` is applied so that the list only shows unit names that start characters `sys-k`.

```
$ systemctl list-units 'sys-k*'
UNIT                     LOAD   ACTIVE SUB     DESCRIPTION                     
sys-kernel-config.mount  loaded active mounted Kernel Configuration File System
sys-kernel-debug.mount   loaded active mounted Kernel Debug File System        
sys-kernel-tracing.mount loaded active mounted /sys/kernel/tracing             

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

3 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
```

=== systemctl list-unit-files

`systemctl [options] list-unit-files <pattern>`

Lists a unit's associated file. Unit files are listed with the following columns:

* `UNIT FILE` – the name of a the file
* `STATE` – the state of the file. Value can be `static`, `generated` or `disabled`

A unit file describes how a systemd will start and run a unit.

*Example:*

The following example lists unit files using the filer `sys-*` to show only those file names that begin with the characters `sys-`.

```
$ systemctl list-unit-files 'sys-*'
UNIT FILE                     STATE 
sys-fs-fuse-connections.mount static
sys-kernel-config.mount       static
sys-kernel-debug.mount        static

3 unit files listed.
```


