= Advanced Linux Commands Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

The following is a sampling of advanced Linux commands typically used by developers. The commands are organized according to category

== application management commands

=== systemctl

`systemctl [options] <subcommand>`

The command `systemctl` is used to introspect and control the state of the `systemd` suite of Linux system components.

**Examples:**

The following example shows the invocation and result of `systemctl status` command set that discovers the status of the Apache Web Server. (`$` is the command prompt symbol.)

```
$ systemctl status httpd
â— httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; disabled; vendor preset: disable>
   Active: inactive (dead)
     Docs: man:httpd.service(8)
```

The following example shows the invocation `systemctl start` command set that start the `mariadb` database.

`systemctl start mariadb`

The following example shows the invocation `systemctl enable` command set to make it so that the particular application starts automatically when the computer reboots.

`systemctl enable mariadb`


=== yum

`yum` is the application installation and removal tool for Fedora, Centos and RHEL.

*Example:*

The following command installs `net-tools` application which has many handy utilities such as `netstat`.

`sudo yum -y install net-tools`


== audit commands

=== ausearch

`ausearch [options] <application/process>`

The `ausearch` command is a tool that can query the audit logs according to events defined by different search criteria.

**Example:**

The following example shows how to use `ausearch` to get information about the user named `root` from the audit logs. The  option `-ui` indicates the the search should be conducted according to a particular userid, in this case `root`. The result is piped to the `more` command that has the option `-10` which indicates to show the first ten lines of output.

The `ausearch` command must be invoked as `sudo` in order to access audit logs. (`$` is the command prompt symbol.)

```
$ sudo ausearch -ui root | more -10
----
time->Fri Jan  7 15:42:52 2022
type=SERVICE_START msg=audit(1641598972.323:5): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=rpcbind comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
----
time->Fri Jan  7 15:42:52 2022
type=PROCTITLE msg=audit(1641598972.761:6): proctitle=2F7362696E2F617564697463746C002D52002F6574632F61756469742F61756469742E72756C6573
type=SYSCALL msg=audit(1641598972.761:6): arch=c000003e syscall=44 success=yes exit=56 a0=3 a1=7fff0ba65240 a2=38 a3=0 items=0 ppid=843 pid=858 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="auditctl" exe="/usr/sbin/auditctl" subj=system_u:system_r:unconfined_service_t:s0 key=(null)
type=CONFIG_CHANGE msg=audit(1641598972.761:6): op=set audit_backlog_limit=8192 old=64 auid=4294967295 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 res=1
----
--More--
```

== disk management

== df

`df [options] <file name>`

The command `df`` shows the amount of disk space available on the file system containing each the file name that represents a particular disk device mount.   If no file name is given, the space available on all mounted file systems is displayed.

**Example:**

The following example shows the invocation and result of `df` displaying all mounted file systems. Disk space  is  shown in  1K blocks.

```
$ df
Filesystem            1K-blocks    Used Available Use% Mounted on
devtmpfs                3949180       0   3949180   0% /dev
tmpfs                   3978636       0   3978636   0% /dev/shm
tmpfs                   3978636    9464   3969172   1% /run
tmpfs                   3978636       0   3978636   0% /sys/fs/cgroup
/dev/mapper/rhel-root  50065528 5588744  44476784  12% /
/dev/mapper/rhel-home  24445276  228104  24217172   1% /home
/dev/sda1               1038336  262796    775540  26% /boot
tmpfs                    795724      64    795660   1% /run/user/1000
```

=== fdisk

**Example:**

=== fsck

`fsck [options] q<file system>`

The command `fsck` inspects and optionally repairs a disk mount represented by the `file system` argument.

**Example:**

=== mount

**Example:**

== file management commands

=== chmod

`chmod [options] <file or directory>`

**Example:**

=== chown

**Example:**

`chown [options] <file or directory>`

== memory management commands

=== free


**Example:**

```
$ free -w
              total        used        free      shared     buffers       cache   available
Mem:        7957276     1653404     4563456       35032        4320     1736096     5965440
Swap:       8286204           0     8286204
```


== network commands

=== curl

`curl [options] <url>`

Gets or posts a file to/from the internet according to a URL.

**Examples:**

The following example downloads a web page from the Red Hat Developer webs site and implements the `-o` option to save the page to the file `article.html`.

```
$ curl https://developers.redhat.com/articles/2022/01/11/5-design-principles-microservices -o article.html
```

The following example uses the `curl` command to upload a file named `data.txt` to the URL `https://example.com/api/data`.

Notice the use of the `-X` option to tell `curl` to use the HTTP POST method, the `-H` option to set the content type header in the request and the `-d` option to define the file to upload.

```
$ curl -X POST -H "Content-Type: text/plain" -d "data.txt" https://example.com/api/data
```

=== host

**Example:**

```
$ host redhat.com
redhat.com has address 209.132.183.105
redhat.com mail is handled by 10 us-smtp-inbound-1.mimecast.com.
redhat.com mail is handled by 10 us-smtp-inbound-2.mimecast.com.
```

=== hostname

`hostname`

Sets or gets the hostname of the computer or virtual machine

**Examples:**

The following example displays the current hostname of the machine

```
$ hostname
localhost.localdomain
```

The following example renames the current hostname of the machine to `newhostname.localdomain` and then verifies the current hostname of the machine.

```
$ sudo hostname newhostname.localdomain
$ hostname
newhostname.localdomain
```

=== hostnamectl

`hostnamectl [OPTIONS...] <command>`

The command `hostnamectl` is similar to the command `hostname` but with come added capabilities. 

**Example:**

The following example invokes and displays the result of the `hostnamectl status` command set to report hostname and additional information.

```
$ hostnamectl status
   Static hostname: localhost.localdomain
Transient hostname: tempvm.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 7080e8d7b18547fa90aa06416ce6a1cf
           Boot ID: 7d0c3ed3f773457a8045602e66e2581f
    Virtualization: oracle
  Operating System: Red Hat Enterprise Linux 8.5 (Ootpa)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
            Kernel: Linux 4.18.0-348.el8.x86_64
      Architecture: x86-64
```

=== iptables

**Example:**

=== nmvcli

**Example:**

=== ss

**Example:**

== os management commands

=== getenforce

**Example:**

=== getsebool

**Example:**

=== getsebool

**Example:**

=== restorecon

**Example:**

=== semanage

**Example:**

=== setsebool

**Example:**

=== subscription-manager

**Example:**

=== vmstat #

**Example:**

== process management commands

=== bg

**Example:**

=== command && command

**Example:**

=== fg

**Example:**

=== iotop

**Example:**

=== jobs

**Example:**

=== ps

**Example:**

== system information

=== lscpu

**Example:**

=== lshw

**Example:**

=== lshw

**Example:**