= Advanced Linux Commands Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

The following is a sampling of advanced Linux commands typically used by developers. The commands are organized according to category

== application management commands

The following commands apply to working with a computer's applications and executables. 

=== systemctl

`systemctl [options] <subcommand>`

The command `systemctl` is used to inspect and control the state of the `systemd` suite of Linux system components.

**Examples:**

The following example shows the invocation and result of `systemctl status` command set that discovers the status of the Apache Web Server. (`$` is the command-line prompt symbol.)

```
$ systemctl status httpd
â— httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; disabled; vendor preset: disable>
   Active: inactive (dead)
     Docs: man:httpd.service(8)
```

The following example shows the invocation `systemctl start` command set that start the `mariadb` database.

`systemctl start mariadb`

The following example shows the invocation `systemctl enable` command set to make it so that the particular application starts automatically when the computer reboots.

`systemctl enable mariadb`


=== yum

`yum` is the application installation and removal tool for Fedora, Centos and RHEL.

*Example:*

The following command installs `net-tools` application which has many handy utilities such as `netstat`.

`sudo yum -y install net-tools`


== audit commands

The following command applies to working with the audit capabilities provided by the Linux operating system. 

=== ausearch

`ausearch [options] <application/process>`

The `ausearch` command is a tool that can query the audit logs according to events defined by different search criteria.

**Example:**

The following example shows how to use `ausearch` to get information about the user named `root` from the audit logs. The  option `-ui` indicates the the search should be conducted according to a particular userid, in this case `root`. The result is piped to the `more` command that has the option `-10` which indicates to show the first ten lines of output.

The `ausearch` command must be invoked as `sudo` in order to access audit logs. (`$` is the command-line prompt symbol.)

```
$ sudo ausearch -ui root | more -10
----
time->Fri Jan  7 15:42:52 2022
type=SERVICE_START msg=audit(1641598972.323:5): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=rpcbind comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
----
time->Fri Jan  7 15:42:52 2022
type=PROCTITLE msg=audit(1641598972.761:6): proctitle=2F7362696E2F617564697463746C002D52002F6574632F61756469742F61756469742E72756C6573
type=SYSCALL msg=audit(1641598972.761:6): arch=c000003e syscall=44 success=yes exit=56 a0=3 a1=7fff0ba65240 a2=38 a3=0 items=0 ppid=843 pid=858 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="auditctl" exe="/usr/sbin/auditctl" subj=system_u:system_r:unconfined_service_t:s0 key=(null)
type=CONFIG_CHANGE msg=audit(1641598972.761:6): op=set audit_backlog_limit=8192 old=64 auid=4294967295 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 res=1
----
--More--
```

== disk management

The following commands apply to working with disks, devices and volumes on a computer running the Linux operating system. 

=== df

`df [options] <file name>`

The command `df`` shows the amount of disk space used and available according to the file system that represents a particular disk device mount.   If no file name is given, the space available on all mounted file systems is displayed.

**Example:**

The following example shows the invocation and result of `df` displaying all mounted file systems. Disk space  is  shown in  1K blocks. (`$` is the command-line prompt symbol.)

```
$ df
Filesystem            1K-blocks    Used Available Use% Mounted on
devtmpfs                3949180       0   3949180   0% /dev
tmpfs                   3978636       0   3978636   0% /dev/shm
tmpfs                   3978636    9464   3969172   1% /run
tmpfs                   3978636       0   3978636   0% /sys/fs/cgroup
/dev/mapper/rhel-root  50065528 5588744  44476784  12% /
/dev/mapper/rhel-home  24445276  228104  24217172   1% /home
/dev/sda1               1038336  262796    775540  26% /boot
tmpfs                    795724      64    795660   1% /run/user/1000
```

=== fdisk

The command `fdisk` is used for working with disk partitions on a computer's hard drive. You can use `fdisk` to format a partition a new drive. Also, you can use `fdisk` to get information about existing drives/

**Examples:**

The following example invokes `fdisk` to display a print out of partition tables of all devices on the computer as listed in the `/proc/partitions` file:

```
$ sudo fdisk -l
Disk /dev/sda: 80 GiB, 85899345920 bytes, 167772160 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x565c4e2e

Device     Boot   Start       End   Sectors Size Id Type
/dev/sda1  *       2048   2099199   2097152   1G 83 Linux
/dev/sda2       2099200 167772159 165672960  79G 8e Linux LVM

Disk /dev/mapper/rhel-root: 47.8 GiB, 51292143616 bytes, 100179968 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mapper/rhel-swap: 7.9 GiB, 8485076992 bytes, 16572416 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mapper/rhel-home: 23.3 GiB, 25044189184 bytes, 48914432 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

The following examples uses `fdisk` to start the process of formatting and partitioning a drive at `/dev/sda1`. This invocation of `fdisk` will open a dialog in the terminal window that walks the developer through the formatting and partitioning process.

```
fdisk /dev/sda1
```

**Be advised!** Using `fdisk` in this manner erases all data on the disk.

=== mount

`mount [options] <device_directory>``

The `mount` command shows or attaches a devices filesystem to a Linux operating system's master file tree.

**Examples:**

The following example shows the `mount` command using the `-l` option to list all mounted file systems. The result of `mount` is piped to the `more` command. The `more` command using the `-10` option to display the first ten lines of output. (`$` is the command-line prompt symbol.)

```
$ mount -l | more -10
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime,seclabel)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,seclabel,size=3949180k,nr_inodes=987295,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,seclabel)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,seclabel,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-ag
ent,name=systemd)
--More--
```

The following example uses the `mount` command to mount the file system for a hard drive that is represented as `/dev/sda1`. (`$` is the command-line prompt symbol.)

```
$ sudo mount /dev/sda1
```

===  xfs_repair

`xfs_repair [options] <drive>`

The command `xfs_repair` inspects and optionally repairs a hard drive on a computer running RHEL Linux.

**Be advised!** You much unmount the drive using the `umount` command before invoking `xfs_repair`

**Example:**

The following example unmounts a hard drive a `/dev/sda1` and then runs the command `xfs_repair` against that drive. (Note that `$` is the command-prompt symbol.)

```
$ sudo umount /dev/sda1

$ sudo xfs_repair /dev/sda1
Phase 1 - find and verify superblock...
Phase 2 - using internal log
        - zero log...
        - scan filesystem freespace and inode maps...
        - found root inode chunk
Phase 3 - for each AG...
        - scan and clear agi unlinked lists...
        - process known inodes and perform inode discovery...
        - agno = 0
        - agno = 1
        - agno = 2
        - agno = 3
        - process newly discovered inodes...
Phase 4 - check for duplicate blocks...
        - setting up duplicate extent list...
        - check for inodes claiming duplicate blocks...
        - agno = 0
        - agno = 1
        - agno = 2
        - agno = 3
Phase 5 - rebuild AG headers and trees...
        - reset superblock...
Phase 6 - check inode connectivity...
        - resetting contents of realtime bitmap and summary inodes
        - traversing filesystem ...
        - traversal finished ...
        - moving disconnected inodes to lost+found ...
Phase 7 - verify and correct link counts...
done

```
== file management commands

The following commands apply to working with file and directories on a computer running the Linux operating system.

=== chmod

`chmod [options] <file or directory>`

Changes the permissions granted to a file or directory

**Examples:**

The following example applies read-only permissions for all users to the file named `sample.txt`. Then the command `ls -l` is executed for verify that the file is indeed read-only. The output is displayed too.

```
$ chmod a-w+r sample.txt
$ ls -l sample.txt
-r--r--r--. 1 guest guest 32 Jan 17 10:34 sample.txt
```

The following example applies read and write permissions for all users to the file named `sample.txt`. Then the command `ls -l` is executed for verify that the file is indeed read-only. The output is displayed too.

```
$ chmod a+w+r sample.txt
$ ls -l sample.txt
-rw-rw-rw-. 1 guest guest 32 Jan 17 10:34 sample.txt
```
=== chown

`chown [options] <owner><:<:<group>> <file>`

Changes the owner and or group of a given file.

**Example:**

`chown [options] <file or directory>`

== job commands

The following command apply to working with  jobs running under the Linux operating system.

=== bg

`bg<job_id>`

The `bg` command sends a job to the background.

**Example:**

The following example creates a bash script named `demo.sh` that outputs the string `hi there` to the console and then sleeps for 2 seconds. The bash script is invoked as a foreground job.

Then the foreground job is stopped by striking the `,ctrl+Z` keys. The job is started again in the background using the `bg` command along with the job id `%1`.

```
$ echo "while true; do echo hi there; sleep 2; done" > demo.sh
$ sh demo.sh
hi there
hi there
hi there
^Z
[1]+  Stopped                 sh demo.sh
$ bg %1
[1]+ sh demo.sh &
```

=== fg

`fg <job_id>`

The `fg` command sends a job to the foreground.


**Example:**

The following example creates a bash script named `demo.sh` that outputs the string `hi there` to the console and then sleeps for 2 seconds. The script invoked as a job.

Then the foreground job is stopped by striking the `ctrl+Z` keys. The job is started again in the foreground using the `fg` command along with the job id `%1`.

```
$ echo "while true; do echo hi there; sleep 2; done" > demo.sh
$ sh demo.sh
hi there
hi there
hi there
^Z
[1]+  Stopped                 sh demo.sh
$ fg %1
sh demo.sh
```
=== jobs

`jobs [options]`

Lists the jobs invoked from the process window

**Example:**

The following example uses the `jobs` command to list all the jobs and the status of jobs that were started from the current terminal window.

Notice that there are three jobs in force. All the jobs are running the same bash script named `demo.sh`. Jobs %1 and %3 are stopped. Job %2 is running in the background as denoted by the symbol. 

```
$ jobs -l
[1]+  6265 Stopped                 sh demo.sh
[2]   6262 Running                 sh demo.sh &
[3]+  6265 Stopped                 sh demo.sh
```


== memory management commands

The following command applies to working with memory on a computer running the Linux operating system.

=== free

**Example:**

```
$ free -w
              total        used        free      shared     buffers       cache   available
Mem:        7957276     1653404     4563456       35032        4320     1736096     5965440
Swap:       8286204           0     8286204
```

== network commands

The following is a list of commands that apply to working with with or on a network.

=== curl

`curl [options] <url>`

Gets or posts a file to/from the internet according to a URL.

**Examples:**

The following example downloads a web page from the Red Hat Developer webs site and implements the `-o` option to save the page to the file `article.html`.

```
$ curl https://developers.redhat.com/articles/2022/01/11/5-design-principles-microservices -o article.html
```

The following example uses the `curl` command to upload a file named `data.txt` to the URL `https://example.com/api/data`.

Notice the use of the `-X` option to tell `curl` to use the HTTP POST method, the `-H` option to set the content type header in the request and the `-d` option to define the file to upload.

```
$ curl -X POST -H "Content-Type: text/plain" -d "data.txt" https://example.com/api/data
```

=== host

`host [options] <domain_name>`

The `host` command reports information about a given domain name.

**Example:**

The following example uses `host` to report the default information about the domain name `redhat.com`.

```
$ host redhat.com
redhat.com has address 209.132.183.105
redhat.com mail is handled by 10 us-smtp-inbound-1.mimecast.com.
redhat.com mail is handled by 10 us-smtp-inbound-2.mimecast.com.
```

=== hostname

`hostname`

Sets or gets the hostname of the computer or virtual machine

**Examples:**

The following example displays the current hostname of the machine

```
$ hostname
localhost.localdomain
```

The following example renames the current hostname of the machine to `newhostname.localdomain` and then verifies the current hostname of the machine.

```
$ sudo hostname newhostname.localdomain
$ hostname
newhostname.localdomain
```

=== hostnamectl

`hostnamectl [OPTIONS...] <command>`

The command `hostnamectl` is similar to the command `hostname` but with some added capabilities. 

**Example:**

The following example invokes and displays the result of the `hostnamectl status` command set to report hostname and additional information.

```
$ hostnamectl status
   Static hostname: localhost.localdomain
Transient hostname: tempvm.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 7080e8d7b18547fa90aa06416ce6a1cf
           Boot ID: 7d0c3ed3f773457a8045602e66e2581f
    Virtualization: oracle
  Operating System: Red Hat Enterprise Linux 8.5 (Ootpa)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
            Kernel: Linux 4.18.0-348.el8.x86_64
      Architecture: x86-64
```

=== iptables

`iptables [options]`

The command `iptables` sets and monitors network access to a given computer.

**Be advised!** The command `iptables` must be run with administrator permissions under `sudo`.

**Examples:**

The following example allows incoming TCP traffic accessing the computer via port 22.

```
$ sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT
```

The following example rejects any network traffic coming in from a computer running from the IP address `192.168.86.11`

```
$ sudo iptables -A INPUT -s 192.168.86.11 -j DROP
```

=== nmcli

`nmcli [options] <object> <command>`

The application `nmcli` is the command line interface for working with the Linux NetworkManager.

**Examples:**

The following example uses `nmcli` to display the overall connection status of the computer using the `general` object and the `status` command.

```
$ nmcli general status
STATE      CONNECTIVITY  WIFI-HW  WIFI     WWAN-HW  WWAN    
connected  full          enabled  enabled  enabled  enabled 
```

The following example uses `nmcli` to display the connection status the network interface devices using the `device` object and the `status` command.

```
$ sudo nmcli device status
DEVICE      TYPE      STATE                   CONNECTION 
enp0s3      ethernet  connected               enp0s3 
```

The following example uses `nmcli` to display the connection profiles of network devices on a computer in a report-like format by using the option `-p` (pretty) against the `connection` object.

```
$ nmcli -p connection
======================================
  NetworkManager connection profiles
======================================
NAME    UUID                                  TYPE      DEVICE 
------------------------------------------------------------------
enp0s3  c68cddff-4883-4efb-bf7a-8b746fe6b26d  ethernet  enp0s3 
virbr0  49bf2d57-cf45-41a8-85d2-cd43a59f0e1c  bridge    virbr0 
```

== process commands

The following commands apply to working with Linux process from the command line.

=== &&

**Example:**

TO BE PROVIDED

=== iotop

**Example:**

TO BE PROVIDED

=== ps

**Example:**

TO BE PROVIDED


== SELinux management commands
The following commands apply to working RedHat's Security Enhanced Linux (SELinux). SELinux provides an additional layer of system security. SELinux fundamentally answers the question: "May <subject> do <action> to <object>", for example: "May a web server access files in users' home directories?".

=== getenforce

`getenforce`

The command `getenforce` reports the current mode of SELinux rules enforcement. The modes are `Enforcing`, `Permissive` or `Disabled`

**Example:**

The following example invokes the command `getenforce` along with the results. (`$` is the command-line prompt symbol.)

```
$ getenforce
Enforcing
```

=== getsebool

`getsebool [-a] <boolean_value>`

The command `getsebool` reports whether applicable SELinux setting is `on` or `off` Use `-a` option to show the boolean values of all setting.

**Examples:**

The following example use `getsebool` to show the value of the SELinux setting `virt_use_xserver`.

```
$ getsebool virt_use_xserver
virt_use_xserver --> off
```

The following example use `getsebool` along with piping the result to the `grep` and then `more` commands to show all SELinux settings that have the value `on`. The `more` command uses the `-10` option to show the first ten lines of output. 

```
$ getsebool -a | grep "on$" | more -10
abrt_upload_watch_anon_write --> on
auditadm_exec_content --> on
boinc_execmem --> on
cron_userdomain_transition --> on
dbadm_exec_content --> on
domain_fd_use --> on
entropyd_use_audio --> on
fips_mode --> on
gssd_read_tmp --> on
guest_exec_content --> on
--More--
```

=== restorecon

`restorecon [options] </path/to/dirctory_or_filename>`

The command `restorecon` is  used to set the security context (extended SELinux file labels) on one or more files to the default setting.


**Example:**

The following example uses `restorecon` to restore the default labels on all files under the directory `/var/www/html`. The option `-F` is used to force a change. The option `v` will show changes in a file's lables. The option `-R` implements execution of the command recursively through all subordinate directories and files from the directory where the command invoked.

```
$ restorecon -FvR /var/www/html
```

=== semanage

`semanage <object> [options]`

The `semanage` command allows adminstrators to manage SELinux capabilities according to the particular object of interet. Each object will have its own set of options. Example of `semanage` objects are `user`, `login`, `port` and `fcontext` to name a few.

The command must be invoked as `sudo`.

The `semanage` program does not ship with SELinux by default. You must install the policycoreutils-python package with yum to get the `semanage` command.

**Examples:**

The following example uses `semanage` to get the security settings for the `user` objects. The `-l` option is used to list the information for all users. T

```
$ sudo semanage user -l

                Labeling   MLS/       MLS/                          
SELinux User    Prefix     MCS Level  MCS Range                      SELinux Roles

guest_u         user       s0         s0                             guest_r
root            user       s0         s0-s0:c0.c1023                 staff_r sysadm_r system_r unconfined_r
staff_u         user       s0         s0-s0:c0.c1023                 staff_r sysadm_r unconfined_r
sysadm_u        user       s0         s0-s0:c0.c1023                 sysadm_r
system_u        user       s0         s0-s0:c0.c1023                 system_r unconfined_r
unconfined_u    user       s0         s0-s0:c0.c1023                 system_r unconfined_r
user_u          user       s0         s0                             user_r
xguest_u        user       s0         s0                             xguest_r
```

The following example uses `semanage` to view a list login information.

```
$ sudo semanage login -l

Login Name           SELinux User         MLS/MCS Range        Service

__default__          unconfined_u         s0-s0:c0.c1023       *
root                 unconfined_u         s0-s0:c0.c1023       *
```

=== setsebool

`setsebool <setting> <value>`

The `setsebool` applies a boolean value to an SELinux setting.

**Example:**

The following example uses `setsebool` to apply the value `1` (`true`) to the SELinux setting `httpd_can_network_connect_db`.

```
$ setsebool httpd_can_network_connect_db 1
```

=== subscription-manager

`subscription-manager <command> [options]`

The `subscription-manager` is the command line version of the graphical RHEL Subscription Manager. The Subscription Manager is a service that keeps track of the Red Hat products and subscriptions installed on the local computer. Subscription Manager communicates with the subscription service on the backend. Typically backend settings are managed via the Customer Portal or an on-premise server such as Subscription Asset Manager.  The Subscription Managed works with content management tools such as `yum`.

The command `subscription-manager` will run as the root user, thus password prompt will be presented upon invocation.

**Example:**

The following example uses the `subscription-manager facts` command set to get facts about the local computer. The command pipes the result the `more` command which in turn uses the `-15` option to display the first 15 lines of output.
```
$ sudo subscription-manager facts | more -15
Password: You are attempting to run "subscription-manager" which requires administrative
Password: 

cpu.core(s)_per_socket: 1
cpu.cpu(s): 1
cpu.cpu_socket(s): 1
cpu.thread(s)_per_core: 1
cpu.topology_source: kernel /sys cpu sibling lists
distribution.id: Ootpa
distribution.name: Red Hat Enterprise Linux
distribution.version: 8.5
distribution.version.modifier: Unknown
dmi.baseboard.manufacturer: Oracle Corporation
dmi.baseboard.product_name: VirtualBox
dmi.baseboard.serial_number: 0
dmi.baseboard.version: 1.2
dmi.bios.address: 0xe0000
dmi.bios.release_date: 12/01/2006
--More--
```

=== vmstat #

`vmstat [options]`

The command `vmstat` reports information about virtual memory usage as well as other relevant system data.

**Example:**

The following command invokes the `vmstat` command with the `--stats` option to display virtual memory and system information for the local virtual machine.

```
$ vmstat --stats
      7957276 K total memory
      1947752 K used memory
       999836 K active memory
      2537556 K inactive memory
      4001688 K free memory
         5248 K buffer memory
      2002588 K swap cache
      8286204 K total swap
            0 K used swap
      8286204 K free swap
        20330 non-nice user cpu ticks
         1964 nice user cpu ticks
        21780 system cpu ticks
     92624051 idle cpu ticks
        23290 IO-wait cpu ticks
        83766 IRQ cpu ticks
        38878 softirq cpu ticks
            0 stolen cpu ticks
      1077302 pages paged in
      1956245 pages paged out
            0 pages swapped in
            0 pages swapped out
     42443346 interrupts
     82932549 CPU context switches
   1641598949 boot time
       202862 forks
```


== system information

=== lscpu

**Example:**

TO BE PROVIDED

=== lshw

**Example:**

TO BE PROVIDED

=== lshw

**Example:**

TO BE PROVIDED

== users and groups

=== useradd

`adduser [options] <username>`

Adds a user to the computing environment

**Example:**

TO BE PROVIDED

=== deluser

`userdel [options] <username>`

Deletes a user from the computer

**Example:**

TO BE PROVIDED

=== groupadd

`groupadd [options] <groupname>`

Adds a group to the computer

**Example:**

TO BE PROVIDED

=== groupdel

`groupdel [options] <groupname>`

Deletes a group from the computer

**Example:**

TO BE PROVIDED

