= Linux Commands Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

Easy to use Linux shortcuts for developers organized according to category

== application management

=== yum

`yum` is the application installation tool for Fedora, Centos and RHEL.

*Example:*

The following command installs `net-tools` application which has many handy utilities such as `netstat`.

`sudo yum -y install net-tools`

== console and output management

=== cat

`cat <path/to/filename>` Displays the contents of `<path/to/filename>` to standard out

*Example:*

The following command displays the contents of the system-release file that the describes the version of RHEL, Centos or Fedora that's running.

```
$ cat /etc/system-release
Red Hat Enterprise Linux release 8.5 (Ootpa)
```


=== clear

Clear the terminal screen

=== echo

`echo <string>`

Displays a string to stdout by default

*Example:*

```
$ echo "Hello World"
Hello World
```

=== top

Displays information about the running Linux processes

*Example:*

The following displays the `top` command with the result piped to the `more` command in order to view the first portion of the output.


```
$ top | more
top - 09:39:33 up 4 days, 17:57,  2 users,  load average: 0.05, 0.01, 0.00
Tasks: 201 total,   2 running, 199 sleeping,
   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.
0 id,  0.0 wa,  0.0 hi,  0.0 si,
  0.0 st
MiB Mem :   7770.8 total,   5526.7 free,   1230.0 use
d,   1014.1 buff/cache
MiB Swap:   8092.0 total,   8092.0 free,      0.0 use
d.   6260.8 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                               
   
  67419 reselbob  20   0   65444   5096   4212 R  12.5   0.1   0:00.02 top                                               
       
      1 root      20   0  175932  14212   8924 S   0.0   0.2   0:05.58 systemd                                              
      2 root      20   0       0      0      0 S   0.0   0.0   0:00.10 kthreadd                                             
      3 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_gp                                               
      4 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_par_gp                                           
      6 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/0:0H-events_highpri                          
      9 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 mm_percpu_wq                                           
     10 root      20   0       0      0      0 S   0.0   0.0   0:02.22 ksoftirqd/0                                              
     11 root      20   0       0      0      0 I   0.0   0.0   0:00.93 rcu_sched                                            
    
--More--
```

== environment variables

=== env

Displays all environment variables running on system

=== export

Creates an environment variable with a value and then exports the environment variable/value pair to the system.

*Example:*

The following command creates an environment variable named `WEB_PAGE` and sets the value to `https://www.redhat.com/en`. Then the `echo` command is used to confirm the value of the environment variable.


```
$ export WEB_PAGE="https://www.redhat.com/en"
$ echo $WEB_PAGE
https://www.redhat.com/en
```

=== source

`source </path/to/filename>`

The `source` command executes commands stored in a file from within the current shell. The `source` command can be used to refresh environment variables.

By default a new shell is launched to run a script, therefore changes to environment variables are not visible in the current shell.

*Example:*

The following example uses the `cat` command to create a file named `new_vars.sh`. The file contains an `export` instruction set for the environment variable `ALT_USER=barry`. Then the `source` command is called to set the environment variable into the system. The `echo` command is called to verify that the environment variable `ALT_USER` is in force. (`$` indicates the command prompt.)

```
$ cat <<EOF > new_vars.sh
> #!/bin/bash
> export ALT_USER=barry
> EOF
$ source ./new_vars.sh
$ echo $ALT_USER
barry

```

== file and directory management

=== cd

`cd </path/to/directory>`

Change to another current directory

*Example:*

The following example change the current directory to the user's home directory

`cd ~/`

=== cp

`cp </path/to/source/filename> </path/to/target/filename>`

Copies the contents of the source directory or file to a target directory or file.

*Example:*

The following example copies the contents of the file `helloworld.txt` to the file named `helloworld.bak` and then executes the `cat` command to verify that the file and it's contents have been copied.

```
$ cp helloworld.txt helloworld.bak
$ cat helloworld.bak 
Hello World!
```

=== find

`sudo find <starting/directory> -name <file/directory name>`

Finds a file or directory by name

*Example:*

The following command finds a file named `hostname` starting from the root (`/`) directory of the computer's file system. The command starts with the `sudo` in order to access files restricted to the `root` user.

```
$ sudo find / -name hostname
/proc/sys/kernel/hostname
/etc/hostname
/var/lib/selinux/targeted/active/modules/100/hostname
/usr/bin/hostname
/usr/lib64/gettext/hostname
/usr/share/licenses/hostname
/usr/share/doc/hostname
/usr/share/bash-completion/completions/hostname
/usr/share/selinux/targeted/default/active/modules/100/hostname
/usr/libexec/hostname
```

=== grep

`grep <search_expression> <input>`

Searches plain-text input from a file or stdout according according to a regular expression

*Example:*

The following example searches the file `/etc/password` for lines that have the string `ftp`.

```
$ grep ftp /etc/passwd
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
```

=== head

`head </path/to/filename>`

Outputs the first part of a file (first 10 lines)

*Example:*

The following example uses the command `head` to output the first ten lines of the file `~/.bashrc`.

```
$ head ~/.bashrc
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
```

=== less

`less [options] </path/to/filename>`

The `less` command allows you to view and navigate the contents of a plain text file or stdout in a controlled manner. Once you open a file using `less` you can navigate the file using the following keystrokes.

* Scroll forward: `Ctrl-f`
* Scroll backward: `Ctrl-b`
* End of file: `G`
* Quit less: `q`

*Example:*

The following example uses the `less` command to open file `~/.bashrc` and to display the file with line numbers using the option `-N`.

```
$ less -N ~/.bashrc
```

Result:

```
1 # .bashrc
2 
3 # Source global definitions
4 if [ -f /etc/bashrc ]; then
5         . /etc/bashrc
6 fi
7 
8 # User specific environment
9 if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
10 then
11     PATH="$HOME/.local/bin:$HOME/bin:$PATH"
12 fi
13 export PATH
14 
15 # Uncomment the following line if you don't like systemctl's auto-paging feature:
16 # export SYSTEMD_PAGER=
17 
18 # User specific aliases and functions
19 PS1="$ "
```

=== ls

`ls [options] </path/to/directory>`

Lists the contents of a directory. Defaults to the current directory.

*Examples:*

List all the directories in the current directory.

```
$ ls 
code  docs  images
```

List all the files and directories in the current directory along using long listing option `-l`.

```
$ ls -l
total 0
drwxrwxr-x. 2 reselbob reselbob  6 Jan 12 11:33 code
drwxrwxr-x. 2 reselbob reselbob 25 Jan 12 11:37 docs
drwxrwxr-x. 2 reselbob reselbob  6 Jan 12 11:34 images
```

List all the files and directories in the current directory along with the hidden files using long listing option `-l` and the show hidden files option `-a`.

```
$ ls -la
total 4
drwxrwxr-x. 5 reselbob reselbob 60 Jan 12 11:36 .
drwxr-xr-x. 3 reselbob reselbob 68 Jan 12 11:33 ..
drwxrwxr-x. 2 reselbob reselbob  6 Jan 12 11:33 code
drwxrwxr-x. 2 reselbob reselbob 25 Jan 12 11:37 docs
drwxrwxr-x. 2 reselbob reselbob  6 Jan 12 11:34 images
-rw-rw-r--. 1 reselbob reselbob 15 Jan 12 11:36 .secrets
```

list all the files and directories in the subdirectory named `docs` using long listing option `-l`.

```
$ ls -l docs
total 4
drwxrwxr-x. 2 reselbob reselbob  6 Jan 12 11:44 drafts
-rw-rw-r--. 1 reselbob reselbob 49 Jan 12 11:37 hithere.txt
-rw-rw-r--. 1 reselbob reselbob  0 Jan 12 11:45 notes.txt
```

=== mkdir

Creates a directory

=== more

=== mv

Moves a file or directory

=== pwd

Displays the name of the present working directory.

=== rm

Removes a file or directory.

=== tar

== help

=== man

`man <path/to/command>`

== network

=== curl

Gets a file from the internet according to a URL.

=== ip

Get the IP address information for the physical or virtual machine.

=== netstat

=== ssh

Secure shell, an encrypted network protocol allowing for remote login and command execution

On Windows: PuTTY and WinSCP

An “ssh.exe” is also available via Cygwin as well as with a Git installation.

=== wget

== process management

=== &

=== kill

=== ps

=== which

== system control

=== poweroff

=== restart

== user management

=== whomai