= Linux Commands Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

Easy to use Linux shortcuts for developers organized according to category

== application management commands

=== yum

`yum` is the application installation tool for Fedora, Centos and RHEL.

*Example:*

The following command installs `net-tools` application which has many handy utilities such as `netstat`.

`sudo yum -y install net-tools`

== console and output management commands

=== cat

`cat <path/to/filename>` Displays the contents of `<path/to/filename>` to standard out

*Example:*

The following command displays the contents of the system-release file that the describes the version of RHEL, Centos or Fedora that's running.

```
$ cat /etc/system-release
Red Hat Enterprise Linux release 8.5 (Ootpa)
```


=== clear

Clear the terminal screen

=== echo

`echo <string>`

Displays a string to stdout by default

*Example:*

```
$ echo "Hello World"
Hello World
```

=== top

Displays information about the running Linux processes

*Example:*

The following displays the `top` command with the result piped to the `more` command in order to view the first portion of the output.


```
$ top | more
top - 09:39:33 up 4 days, 17:57,  2 users,  load average: 0.05, 0.01, 0.00
Tasks: 201 total,   2 running, 199 sleeping,
   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.
0 id,  0.0 wa,  0.0 hi,  0.0 si,
  0.0 st
MiB Mem :   7770.8 total,   5526.7 free,   1230.0 use
d,   1014.1 buff/cache
MiB Swap:   8092.0 total,   8092.0 free,      0.0 use
d.   6260.8 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                               
   
  67419 reselbob  20   0   65444   5096   4212 R  12.5   0.1   0:00.02 top                                               
       
      1 root      20   0  175932  14212   8924 S   0.0   0.2   0:05.58 systemd                                              
      2 root      20   0       0      0      0 S   0.0   0.0   0:00.10 kthreadd                                             
      3 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_gp                                               
      4 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_par_gp                                           
      6 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/0:0H-events_highpri                          
      9 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 mm_percpu_wq                                           
     10 root      20   0       0      0      0 S   0.0   0.0   0:02.22 ksoftirqd/0                                              
     11 root      20   0       0      0      0 I   0.0   0.0   0:00.93 rcu_sched                                            
    
--More--
```

== environment variables commands

=== env

Displays all environment variables running on system

=== export

Creates an environment variable with a value and then exports the environment variable/value pair to the system.

*Example:*

The following command creates an environment variable named `WEB_PAGE` and sets the value to `https://www.redhat.com/en`. Then the `echo` command is used to confirm the value of the environment variable.


```
$ export WEB_PAGE="https://www.redhat.com/en"
$ echo $WEB_PAGE
https://www.redhat.com/en
```

=== source

`source </path/to/filename>`

The `source` command executes commands stored in a file from within the current shell. The `source` command can be used to refresh environment variables.

By default a new shell is launched to run a script, therefore changes to environment variables are not visible in the current shell.

*Example:*

The following example uses the `cat` command to create a file named `new_vars.sh`. The file contains an `export` instruction set for the environment variable `ALT_USER=barry`. Then the `source` command is called to set the environment variable into the system. The `echo` command is called to verify that the environment variable `ALT_USER` is in force. (`$` indicates the command prompt.)

```
$ cat <<EOF > new_vars.sh
> #!/bin/bash
> export ALT_USER=barry
> EOF
$ source ./new_vars.sh
$ echo $ALT_USER
barry

```

== file and directory management

=== cd

`cd </path/to/directory>`

Change to another current directory

*Example:*

The following example change the current directory to the user's home directory

`cd ~/`

=== cp

`cp </path/to/source/filename> </path/to/target/filename>`

Copies the contents of the source directory or file to a target directory or file.

*Example:*

The following example copies the contents of the file `helloworld.txt` to the file named `helloworld.bak` and then executes the `cat` command to verify that the file and it's contents have been copied.

```
$ cp helloworld.txt helloworld.bak
$ cat helloworld.bak 
Hello World!
```

=== find

`sudo find <starting/directory> -name <file/directory name>`

Finds a file or directory by name

*Example:*

The following command finds a file named `hostname` starting from the root (`/`) directory of the computer's file system. The command starts with the `sudo` in order to access files restricted to the `root` user.

```
$ sudo find / -name hostname
/proc/sys/kernel/hostname
/etc/hostname
/var/lib/selinux/targeted/active/modules/100/hostname
/usr/bin/hostname
/usr/lib64/gettext/hostname
/usr/share/licenses/hostname
/usr/share/doc/hostname
/usr/share/bash-completion/completions/hostname
/usr/share/selinux/targeted/default/active/modules/100/hostname
/usr/libexec/hostname
```

=== grep

`grep <search_expression> <input>`

Searches plain-text input from a file or stdout according according to a regular expression

*Example:*

The following example searches the file `/etc/password` for lines that have the string `ftp`.

```
$ grep ftp /etc/passwd
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
```

=== head

`head </path/to/filename>`

Outputs the first part of a file (first 10 lines)

*Example:*

The following example uses the command `head` to output the first ten lines of the file `~/.bashrc`.

```
$ head ~/.bashrc
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
```

=== less

`less [options] </path/to/filename>`

The `less` command allows you to view and navigate the contents of a plain text file or stdout in a controlled manner. Once you open a file using `less` you can navigate the file using the following keystrokes.

* Scroll forward: `Ctrl-f`
* Scroll backward: `Ctrl-b`
* End of file: `G`
* Quit less: `q`

*Example:*

The following example uses the `less` command to open file `~/.bashrc` and to display the file with line numbers using the option `-N`.

```
$ less -N ~/.bashrc
```

Result:

```
1 # .bashrc
2 
3 # Source global definitions
4 if [ -f /etc/bashrc ]; then
5         . /etc/bashrc
6 fi
7 
8 # User specific environment
9 if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
10 then
11     PATH="$HOME/.local/bin:$HOME/bin:$PATH"
12 fi
13 export PATH
14 
15 # Uncomment the following line if you don't like systemctl's auto-paging feature:
16 # export SYSTEMD_PAGER=
17 
18 # User specific aliases and functions
19 PS1="$ "
```

=== ls

`ls [options] </path/to/directory>`

Lists the contents of a directory. Defaults to the current directory.

*Examples:*

List all the directories in the current directory.

```
$ ls 
code  docs  images
```

List all the files and directories in the current directory along using long listing option `-l`.

```
$ ls -l
total 0
drwxrwxr-x. 2 reselbob reselbob  6 Jan 12 11:33 code
drwxrwxr-x. 2 reselbob reselbob 25 Jan 12 11:37 docs
drwxrwxr-x. 2 reselbob reselbob  6 Jan 12 11:34 images
```

List all the files and directories in the current directory along with the hidden files using long listing option `-l` and the show hidden files option `-a`.

```
$ ls -la
total 4
drwxrwxr-x. 5 reselbob reselbob 60 Jan 12 11:36 .
drwxr-xr-x. 3 reselbob reselbob 68 Jan 12 11:33 ..
drwxrwxr-x. 2 reselbob reselbob  6 Jan 12 11:33 code
drwxrwxr-x. 2 reselbob reselbob 25 Jan 12 11:37 docs
drwxrwxr-x. 2 reselbob reselbob  6 Jan 12 11:34 images
-rw-rw-r--. 1 reselbob reselbob 15 Jan 12 11:36 .secrets
```

list all the files and directories in the subdirectory named `docs` using long listing option `-l`.

```
$ ls -l docs
total 4
drwxrwxr-x. 2 reselbob reselbob  6 Jan 12 11:44 drafts
-rw-rw-r--. 1 reselbob reselbob 49 Jan 12 11:37 hithere.txt
-rw-rw-r--. 1 reselbob reselbob  0 Jan 12 11:45 notes.txt
```

=== mkdir

`cd <directory_name>`

Creates a directory

*Example:*

Creates a new directory named `documents` in the users home directory.

`mkdir ~/documents`

=== more

`more [options] </path/to/filename or stdout>`

Allows a user to view and traverse the content of a file or stdout. The command `more` invokes in a process the displays a command line user interface. The exit the process users strike the `q` key.

**Examples:**

The following example show using the `more` command to display the first 4 lines of the file `/etc/passwd `. Then users can traverse through the rest of the file a line at time by striking the `<ENTER>` key.

```
$ more -4 /etc/passwd 
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
--More--(5%)
```

The following example illustrates using the `more` command to process stdout data. The example pipes the result of running the `ls` against the directory `/etc`. The command `more` displays the first 4 lines of the output from stdout as declared in the option `-4`.

Users can traverse through the rest of stdout a line at time by striking the `<ENTER>` key.

```
$ ls /etc | more -4
accountsservice
adjtime
aliases
alsa
--More--
```

=== mv

`mv <source file/directory> <target file/directory>`

Moves a file or directory. The `mv` command transfers all the contents from the source file or directory to the new location.

**Examples:**

The following example moves the directory `documents` to the directory `docs-bak`. When `move` is invokes the source directory will be renamed `docs-bak`.

`mv ./documents ./docs-bak`

The following example moves the contents of the file `hithere.txt` in the directory `documents` to a file named `new_hithere.txt` in the same directory.

`mv ./documents/hithere.txt ./documents/new_hithere.txt`

=== pwd

`pwd`

Displays the name of the present working directory.

**Example:**

The following example displays the invocation and result of using the command `pwd` in the `HOME` directory for a user named `guest`

```
$ pwd
/home/guest
```

=== rm

`rm [options] <file or directory>`

Removes a file or directory.

**Examples:**

The following example removes the file named `hithere.txt` from the current directory. (`$` indicates the command line prompt.)

```
$ rm hithere.txt
```

The following example removes the directory named `documents` along with all the files and subdirectories. The options `-rf` **f**orce the removal **r**ecursively. 

```
$ rm -rf ./documents
```
=== tar

`tar [options] <archive filename> <file or directory to be compressed>`

Compresses and decompresses files or directories.

**Examples:**

The following example compresses a directory named `documents`, shows the output of the `tar` command and then invokes the `ls` command to list the contents of the current directory.

```
$ tar cvzf docs.tar.gz documents/
documents/
documents/1.txt
documents/2.txt
documents/3.txt
documents/4.txt

$ ls
docs.tar.gz  documents
```

The following example extracts the contents of the compressed file `docs.tar.gz` in to an existing directory named `new-docs`.

```
$ tar -xvf docs.tar.gz -C  ./new-docs
```

== help commands

=== man

`man <path/to/command>`

Display the internal help documentation for a given command.

**Example:**

The following example shows how to display the command line help documentation for the command `cp`;

```
$ man cp
```

== network commands

=== curl

`curl [options] <url>`

Gets or posts a file to/from the internet according to a URL.

**Examples:**

The following example downloads a web page from the Red Hat Developer webs site and implements the `-o` option to save the page to the file `article.html`.

```
$ curl https://developers.redhat.com/articles/2022/01/11/5-design-principles-microservices -o article.html
```

The following example uses the `curl` command to upload a file named `data.txt` to the URL `https://example.com/api/data`.

Notice the use of the `-X` option to tell `curl` to use the HTTP POST method, the `-H` option to set the content type header in the request and the `-d` option to define the file to upload.

```
$ curl -X POST -H "Content-Type: text/plain" -d "data.txt" https://example.com/api/data
```

=== ip

`ip [ OPTIONS ] OBJECT { COMMAND | help }`

Gets the IP information for the physical or virtual machine.

**Example:**

The following example returns the IP address information associated with network interfaces on the current machine.

```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:45:95:d3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.86.34/24 brd 192.168.86.255 scope global dynamic noprefixroute enp0s3
       valid_lft 80971sec preferred_lft 80971sec
    inet6 fe80::a00:27ff:fe45:95d3/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:f7:2c:71 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
4: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:f7:2c:71 brd ff:ff:ff:ff:ff:ff
```

=== netstat


=== ssh

`ssh [options] <ip_address>`

Secure shell, an encrypted network protocol allowing for remote login and command execution

On Windows: PuTTY and WinSCP

An “ssh.exe” is also available via Cygwin as well as with a Git installation.

**Example:**

The following example shows how to use `ssh` to login to a remote computer that has the ip address `192.168.86.11`

```
$ ssh 192.168.86.11
```

=== wget

`wget [options] <url>`

Downloads files from the internet. Supports HTTP, HTTPS, and FTP protocols. You can use wget as an alternative to `curl`.

**Example:**

The following example uses the `wget` command to download a file from the URL `https://developers.redhat.com/articles/2022/01/11/5-design-principles-microservices` and uses the `-o` options to save the content to a file named `article.html`

```
$ wget https://developers.redhat.com/articles/2022/01/11/5-design-principles-microservices -o article.html
```

== process management commands

=== &&

`<command> && <command>`

Executes command in a sequence

**Example:**

The following changes the current directory to `/etc` and then executes the command `ls` to list the contents of the directory.

```
$ cd /etc && ls
```

=== kill

`kill <process_id>`

Removes a running process from memory.

**Example:**

=== ps

`ps [options]`

Displays the status of the current processes.

The following example invokes the `ps command` with the options `aux` to display every process on the system. The result of the invocation is piped to the `more` command using the `-10` to display the first ten lines of results for stdout.

**Example:**

```
$ ps aux | more -10
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.1 175932 14212 ?        Ss   Jan07   0:06 /usr/lib/systemd/systemd --switched-root --syst
em --deserialize 18
root           2  0.0  0.0      0     0 ?        S    Jan07   0:00 [kthreadd]
root           3  0.0  0.0      0     0 ?        I<   Jan07   0:00 [rcu_gp]
root           4  0.0  0.0      0     0 ?        I<   Jan07   0:00 [rcu_par_gp]
root           6  0.0  0.0      0     0 ?        I<   Jan07   0:00 [kworker/0:0H-events_highpri]
root           9  0.0  0.0      0     0 ?        I<   Jan07   0:00 [mm_percpu_wq]
root          10  0.0  0.0      0     0 ?        S    Jan07   0:02 [ksoftirqd/0]
root          11  0.0  0.0      0     0 ?        I    Jan07   0:01 [rcu_sched]
--More--

```
=== which

`which <command>`

Describes the location of a command. If a command is not installed on the computer and its parent directory is not part of the system's `$PATH`, the command will report an error.

**Example:**

The following example invokes the `which` command against the command `clear` and shows the result of the `which` command.

```
$ which clear
/usr/bin/clear 
```

== system control commands

=== poweroff

`poweroff`

Shuts down a computer. (Must be run as `sudo`.)

**Example:**

(`$` indicates the command line prompt)

```
$ sudo poweroff
```

=== restart

`restart`

Restarts a computer. (Must be run as `sudo`.)

**Example:**

(`$` indicates the command line prompt)

```
$ sudo restart
```

== user management commands

=== whomai