= Linux Commands Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

Easy to use Linux shortcuts for developers organized according to category

== application management

=== yum

`yum` is the application installation tool for Fedora, Centos and RHEL.

*Example:*

The following command installs `net-tools` application which has many handy utilities such as `netstat`.

`sudo yum -y install net-tools`

== console and output management

=== cat

`cat <path/to/filename>` Displays the contents of `<path/to/filename>` to standard out

*Example:*

The following command displays the contents of the system-release file that the describes the version of RHEL, Centos or Fedora that's running.

```
$ cat /etc/system-release
Red Hat Enterprise Linux release 8.5 (Ootpa)
```


=== clear

Clear the terminal screen

=== echo

`echo <string>`

Displays a string to stdout by default

*Example:*

```
$ echo "Hello World"
Hello World
```

=== top

Displays information about the running Linux processes

*Example:*

The following displays the `top` command with the result piped to the `more` command in order to view the first portion of the output.


```
$ top | more
top - 09:39:33 up 4 days, 17:57,  2 users,  load average: 0.05, 0.01, 0.00
Tasks: 201 total,   2 running, 199 sleeping,
   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.
0 id,  0.0 wa,  0.0 hi,  0.0 si,
  0.0 st
MiB Mem :   7770.8 total,   5526.7 free,   1230.0 use
d,   1014.1 buff/cache
MiB Swap:   8092.0 total,   8092.0 free,      0.0 use
d.   6260.8 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                               
   
  67419 reselbob  20   0   65444   5096   4212 R  12.5   0.1   0:00.02 top                                               
       
      1 root      20   0  175932  14212   8924 S   0.0   0.2   0:05.58 systemd                                              
      2 root      20   0       0      0      0 S   0.0   0.0   0:00.10 kthreadd                                             
      3 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_gp                                               
      4 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_par_gp                                           
      6 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/0:0H-events_highpri                          
      9 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 mm_percpu_wq                                           
     10 root      20   0       0      0      0 S   0.0   0.0   0:02.22 ksoftirqd/0                                              
     11 root      20   0       0      0      0 I   0.0   0.0   0:00.93 rcu_sched                                            
    
--More--
```

== environment variables

=== env

Displays all environment variables running on system

=== export

Creates an environment variable with a value and then exports the environment variable/value pair to the system.

*Example:*

The following command creates an environment variable named `WEB_PAGE` and sets the value to `https://www.redhat.com/en`. Then the `echo` command is used to confirm the value of the environment variable.


```
$ export WEB_PAGE="https://www.redhat.com/en"
$ echo $WEB_PAGE
https://www.redhat.com/en
```

=== source

`source </path/to/filename>`

The `source` command executes commands stored in a file from within the current shell. The `source` command can be used to refresh environment variables.

By default a new shell is launched to run a script, therefore changes to environment variables are not visible in the current shell.

*Example:*

The following example uses the `cat` command to create a file name `new_vars.sh`.The file contains an `export` instruction set for the environment variable `ALT_USER=barry`. Then the `source` command is called to set the environment variable. The `echo` command is called to verify that the environment variable `ALT_USER` is in force. (`$` indicates the command prompt.)

```
$ cat <<EOF > new_vars.sh
> #!/bin/bash
> export ALT_USER=barry
> EOF
$ source ./new_vars.sh
$ echo $ALT_USER
barry

```

== file and directory management

=== cd

`cd </path/to/directory>`

Change to another current directory

*Example:*

The following example change the current directory to the user's home directory

`cd ~/`

=== cp

`cp </path/to/source/filename> </path/to/target/filename>`

Copies the contents of the source directory or file to a target directory or file.

*Example:*

The following example copies the contents of the file `helloworld.txt` to the file named `helloworld.bak` and then executes the `cat` command to verify that the file and it's contents have been copied.

```
$ cp helloworld.txt helloworld.bak
$ cat helloworld.bak 
Hello World!
```

=== find

=== grep

=== head

=== less

=== ls

=== mkdir

=== more

=== mv

=== pwd

=== rm

=== tar

== help

=== man

== network

=== curl

=== ip

=== netstat

=== ssh

Secure shell, an encrypted network protocol allowing for remote login and command execution

On Windows: PuTTY and WinSCP

An “ssh.exe” is also available via Cygwin as well as with a Git installation.

=== wget

== process management

=== &

=== kill

=== ps

=== which

== system control

=== poweroff

=== restart

== user management

=== whomai