= Linux Commands Cheat Sheet
:experimental: true
:product-name:
:version: 1.0.0

Easy to use Linux shortcuts for developers organized according to category

== application management

=== yum

`yum` is the application installation tool for Fedora, Centos and RHEL.

*Example:*

The following command installs `net-tools` application which has many handy utilities such as `netstat`.

`sudo yum -y install net-tools`

== console and output management

=== cat

`cat <path/to/filename>` Displays the contents of `<path/to/filename>` to standard out

*Example:*

The following command displays the contents of the system-release file that the describes the version of RHEL, Centos or Fedora that's running.

```
$ cat /etc/system-release
Red Hat Enterprise Linux release 8.5 (Ootpa)
```


=== clear

Clear the terminal screen

=== echo

`echo <string>`

Displays a string to stdout by default

*Example:*

```
$ echo "Hello World"
Hello World
```

=== top

Displays the running Linux processes

*Example:*

The following displays the `top` command with the result piped to the `more` command in order to view the first portion of the output.


```
$ top | more
top - 09:39:33 up 4 days, 17:57,  2 users,  load average: 0.05, 0.01, 0.00
Tasks: 201 total,   2 running, 199 sleeping,
   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.
0 id,  0.0 wa,  0.0 hi,  0.0 si,
  0.0 st
MiB Mem :   7770.8 total,   5526.7 free,   1230.0 use
d,   1014.1 buff/cache
MiB Swap:   8092.0 total,   8092.0 free,      0.0 use
d.   6260.8 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                               
   
  67419 reselbob  20   0   65444   5096   4212 R  12.5   0.1   0:00.02 top                                               
       
      1 root      20   0  175932  14212   8924 S   0.0   0.2   0:05.58 systemd                                              
      2 root      20   0       0      0      0 S   0.0   0.0   0:00.10 kthreadd                                             
      3 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_gp                                               
      4 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_par_gp                                           
      6 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/0:0H-events_highpri                          
      9 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 mm_percpu_wq                                           
     10 root      20   0       0      0      0 S   0.0   0.0   0:02.22 ksoftirqd/0                                              
     11 root      20   0       0      0      0 I   0.0   0.0   0:00.93 rcu_sched                                            
    
--More--
```

== environment variables

=== env

=== export

=== source

== file and directory management

=== cd

=== cp

=== find

=== grep

=== head

=== less

=== ls

=== mkdir

=== more

=== mv

=== pwd

=== rm

=== tar

== help

=== man

== network

=== curl

=== ip

=== netstat

=== ssh

Secure shell, an encrypted network protocol allowing for remote login and command execution

On Windows: PuTTY and WinSCP

An “ssh.exe” is also available via Cygwin as well as with a Git installation.

=== wget

== process management

=== &

=== kill

=== ps

=== which

== system control

=== poweroff

=== restart

== user management

=== whomai