= Bash Commands Cheat Sheet
:experimental: true
:product-name: Bash Commands Cheat Sheet

== Bash Script Header

```
#!/usr/bin/env bash
```

== Variables & Strings

=== Variable declaration
```
#!/usr/bin/env bash
MSG="Hello World"
echo "$MSG Alex" # Hello World Alex echo '$MSG Alex' # $MSG Alex
```

*Copy, paste and run in your terminal:*

=== String manipulation
```
MSG="hello world"
# Replace
echo ${MSG/w/W} # hello World
echo ${MSG//[a-zA-Z]/X} # XXXXX XXXXX # Substring
echo ${MSG:0:5} # hello
echo ${MSG%world} # hello
echo ${MSG#hello} # world
# Uppercase
echo ${MSG^} # Hello world
echo ${MSG^^} # HELLO WORLD MSG="HELLO WORLD"
echo ${MSG,} # hELLO WORLD
echo ${MSG,,} # hello world
# Alternative
echo ${MSG:-val} # HELLO WORLD
echo ${FOO:-val} # val
```

== Collections

=== Arrays
```
names=('Alex' 'Ada' 'Alexandra')
names+=('Soto') # Appends element, Soto
unset names[3] # Removes element at index 3, (Soto)

echo ${names[0]} # Alex
echo ${names[1]} # Ada
echo ${names[2]} # Alexandra

# @ indicates all elements in the array
echo ${names[@]} # Alex Ada Alexandra

# Count of names
echo ${#names[@]} # 3
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > arrays-01.sh
#!/usr/bin/env bash

names=('Alex' 'Ada' 'Alexandra')
names+=('Soto') # Appends element, Soto
unset names[3] # Removes element at index 3, (Soto)

echo ${names[0]} # Alex
echo ${names[1]} # Ada
echo ${names[2]} # Alexandra

# @ indicates all elements in the array
echo ${names[@]} # Alex Ada Alexandra

# Count of names
echo ${#names[@]} # 3
EOF
sh arrays-01.sh
```

=== Maps

```
declare -A score
score[alex]="1"
score[edson]="2"
score[sebi]="3"
score[chris]="4"
echo ${!score[@]} # alex edson sebi chris
unset score[chris] # Delete chris entry
echo ${score[@]} # show all the values
echo ${!score[@]} # show all keys
echo ${score[edson]} # show the value of edson: 2
echo ${#score[@]} # show the number of elements in the map: 3
EOF
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > maps-01.sh
#!/usr/bin/env bash

declare -A score
score[alex]="1"
score[edson]="2"
score[sebi]="3"
score[chris]="4"
echo ${!score[@]} # alex edson sebi chris
unset score[chris] # Delete chris entry
echo ${score[@]} # show all the values
echo ${!score[@]} # show all keys
echo ${score[edson]} # show the value of edson: 2
echo ${#score[@]} # show the number of elements in the map: 3
EOF
sh maps-01.sh
```

== Functions

A basic function

```
helloworld() {
  echo "Number of arguments $#" # 2
  echo "Hello World $1 from $2" # Hello World Alex from Bash
  }

helloworld "Alex" "Bash"
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > function-01.sh
#!/usr/bin/env bash

helloworld() {
  echo "Number of arguments $#" # 2
  echo "Hello World $1 from $2" # Hello World Alex from Bash
  }

helloworld "Alex" "Bash"
EOF


sh function-01.sh
```

---

A function that sets a value to a global variable

```
goodmorning () {
  # set a value for the global variable named myresult
  myresult='Good Morning'
 }
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > function-02.sh
#!/usr/bin/env bash

goodmorning () {
  # set a value for the global variable named myresult
  myresult='Good Morning'
 }

goodmorning
echo $myresult
EOF

sh function-02.sh
```

---

A function that returns a numeric code on exit

Exiting with a value of `0` means success. Any higher number means a failure condition by convention

```
myfunc()
{
    echo "this is a message from myfunc()"
    exit 0
}
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > function-03.sh
#!/usr/bin/env bash

myfunc()
{
echo "this is a message from myfunc()"
exit 0
}

# run the custom function named myfunc
myfunc
EOF

sh function-03.sh && echo "$?"
```

A function that returns a numeric code on using return

== Conditional Statements

=== Numeric statements

=== String statements

=== File statements

== Loops

=== Range
```
for i in {1..5}; do
  echo "Hello World $i"
done
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > basic-range-01.sh
#!/usr/bin/env bash

for i in {1..5}; do
  echo "Hello World $i"
done

EOF

sh basic-range-01.sh
```

=== Collections

Print all elements from a plain array:

```
for i in "${names[@]}"; do
  echo "Hello $i"
done
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > range-names-01.sh
#!/usr/bin/env bash

names=('Alex' 'Ada' 'Alexandra', 'Soto')

for i in "${names[@]}"; do
  echo "Hello $i"
done

EOF

sh range-names-01.sh
```

---

Print keys of all elements from a key/value array:

```
for key in "${!score[@]}"; do
  echo $key
done
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > range-keys-01.sh
#!/usr/bin/env bash

declare -A score

score[alex]="1"
score[edson]="2"
score[sebi]="3"
score[chris]="4"

for key in "${!score[@]}"; do
  echo $key
done

EOF
sh range-keys-01.sh
```

---

Print values of all elements from a key/value array:

```
for val in "${score[@]}"; do
  echo $val
done
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > value-keys-01.sh
#!/usr/bin/env bash

declare -A score

score[alex]="1"
score[edson]="2"
score[sebi]="3"
score[chris]="4"

for val in "${score[@]}"; do
  echo $val
done

EOF
sh value-keys-01.sh
```

=== Files and Directories

*Get all files in a directory sub-directories*

The following script gets all files in the directory `/tmp` that have the extension `.log`:

```
for i in /tmp/*.log; do
  echo $i
done
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > files-01.sh
#!/usr/bin/env bash

echo All log files in the /tmp directory

for i in /tmp/*.log; do
  echo $i
done
EOF
sh files-01.sh
```

---

*Get all sub-directories*

The following script gets all subdirectories in the directory `/var`

```
for i in /var/*; do
  echo $(basename "$i")
done
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > files-02.sh
#!/usr/bin/env bash

echo All subdirectories in /var

for i in /var/*; do
  echo $(basename "$i")
done
EOF

sh files-02.sh
```

=== While loop
```
x=1;
while [ $x -le 5 ]; do
  echo "Hello World"
  ((x=x+1))
done
```

*Copy, paste and run in your terminal:*

```
cat << 'EOF' > while-loop-01.sh
#!/usr/bin/env bash

x=1;
while [ $x -le 5 ]; do
  echo "Hello World"
  ((x=x+1))
done
EOF

sh while-loop-01.sh
```

*Copy, paste and run in your terminal:*
== Executing Commands

== Useful Snippets